import type { OfficeDepartmentId } from "@/lib/office/types";

export type DepartmentWorkspaceTabId = "desk" | "pipeline" | "doc" | "table" | "calendar" | "board" | "assets" | "review";

export interface DepartmentWorkspaceProfile {
  departmentId: OfficeDepartmentId;
  workObject: string;
  headline: string;
  primaryViews: string[];
  recordFields: string[];
  primaryActions: string[];
  automationMoments: string[];
  approvalRules: string[];
  connectedApps: string[];
  coworkerRoles: string[];
  doneSignals: string[];
  operatingSurfaces: Array<{
    title: string;
    description: string;
  }>;
  tabs: DepartmentWorkspaceTabId[];
  manualTaskSeeds: string[];
  tableColumns: Array<{
    key: "item" | "owner" | "status" | "next";
    label: string;
    placeholder: string;
  }>;
  pipelineStages: string[];
  artifactKinds: Array<{
    title: string;
    body: string;
    prompt: string;
    kind: "document" | "spreadsheet" | "design" | "video" | "message" | "code" | "payment" | "calendar";
  }>;
  correctionFocus: string;
  aiHandoffVerb: string;
}

const fallbackProfile: DepartmentWorkspaceProfile = {
  departmentId: "general_manager",
  workObject: "work item",
  headline: "Run the room from editable work, records, tasks, and approvals.",
  primaryViews: ["Desk", "Records", "Tasks", "Approvals"],
  recordFields: ["Item", "Owner", "Status", "Next action"],
  primaryActions: ["Review", "Update", "Assign", "Ask Dobly", "Approve"],
  automationMoments: ["New item", "Stalled item", "Approval needed"],
  approvalRules: ["Risky changes pause", "Missing context lowers confidence"],
  connectedApps: ["Docs", "Calendar", "Email"],
  coworkerRoles: ["Room coordinator", "Briefing worker"],
  doneSignals: ["Owner clear", "Next action clear", "Record updated"],
  operatingSurfaces: [
    { title: "Desk", description: "Manual and AI-assisted work items." },
    { title: "Records", description: "Business objects Dobly can watch and update." },
    { title: "Review", description: "Correct output before Dobly learns from it." },
  ],
  tabs: ["desk", "doc", "table", "board", "review"],
  manualTaskSeeds: ["Review open work", "Update next actions", "Prepare owner decision"],
  tableColumns: [
    { key: "item", label: "Item", placeholder: "Work item" },
    { key: "owner", label: "Owner", placeholder: "Owner" },
    { key: "status", label: "Status", placeholder: "Status" },
    { key: "next", label: "Next action", placeholder: "Next action" },
  ],
  pipelineStages: ["Backlog", "Doing", "Review", "Done"],
  artifactKinds: [
    { title: "Document", body: "Draft a brief, SOP, proposal, or summary.", prompt: "Create a working document from this context.", kind: "document" },
    { title: "Tracker", body: "Create a table for owners, status, and next action.", prompt: "Create a tracker from this context.", kind: "spreadsheet" },
  ],
  correctionFocus: "Fix facts, tone, priority, and approval boundaries.",
  aiHandoffVerb: "continue this work",
};

export const DEPARTMENT_WORKSPACE_PROFILES: Partial<Record<OfficeDepartmentId, DepartmentWorkspaceProfile>> = {
  reception: {
    departmentId: "reception",
    workObject: "conversation",
    headline: "Handle the front desk with inbox, calls, bookings, scripts, and escalation controls.",
    primaryViews: ["Omnichannel inbox", "Call log", "Booking calendar", "Escalation queue", "Customer timeline"],
    recordFields: ["Customer", "Channel", "Intent", "Urgency", "Booking need", "Last reply", "Owner decision", "Escalation reason"],
    primaryActions: ["Reply", "Call back", "Book appointment", "Reschedule", "Create lead", "Escalate", "Log customer note"],
    automationMoments: ["Missed call detected", "New WhatsApp inquiry", "Booking requested", "Customer goes quiet", "VIP or complaint phrase appears"],
    approvalRules: ["Refunds pause", "Legal/medical claims pause", "VIP customers pause", "Unclear pricing pauses", "Double-booking is blocked"],
    connectedApps: ["Business phone", "SMS", "WhatsApp Business", "Calendar", "CRM", "Email", "Website chat"],
    coworkerRoles: ["Front desk responder", "Booking assistant", "Missed-call recovery", "Escalation router"],
    doneSignals: ["Customer got a clear answer", "Booking or next step is logged", "CRM/contact record updated", "Escalation has owner context"],
    operatingSurfaces: [
      { title: "Inbox", description: "Calls, WhatsApp, SMS, email, and website chat." },
      { title: "Bookings", description: "Appointment slots, confirmations, reschedules, and no-shows." },
      { title: "Scripts", description: "Greeting, qualification, handoff, and sensitive-response scripts." },
      { title: "Escalations", description: "VIPs, refunds, complaints, and unclear intent." },
    ],
    tabs: ["desk", "pipeline", "doc", "table", "calendar", "review"],
    manualTaskSeeds: ["Review missed-call recovery", "Edit booking script", "Check tomorrow's appointments", "Escalate unclear customer request"],
    tableColumns: [
      { key: "item", label: "Contact", placeholder: "Customer name or number" },
      { key: "owner", label: "Channel", placeholder: "Call, WhatsApp, SMS" },
      { key: "status", label: "State", placeholder: "new, booked, waiting owner" },
      { key: "next", label: "Next reply", placeholder: "Ask availability, qualify, escalate" },
    ],
    pipelineStages: ["New", "Qualifying", "Booked", "Escalated"],
    artifactKinds: [
      { title: "Call script", body: "Greeting, qualification, booking, and escalation flow.", prompt: "Create a reception call script from this department context.", kind: "message" },
      { title: "Booking tracker", body: "Track appointments, confirmations, and no-shows.", prompt: "Create a booking tracker for this reception context.", kind: "calendar" },
      { title: "FAQ replies", body: "Approved answers for common customer questions.", prompt: "Draft FAQ replies for reception.", kind: "document" },
    ],
    correctionFocus: "Correct tone, opening script, booking rules, escalation triggers, and what Dobly must never promise.",
    aiHandoffVerb: "handle the next customer conversation",
  },
  sales: {
    departmentId: "sales",
    workObject: "opportunity",
    headline: "Work leads through pipeline, activities, proposals, quotations, and follow-up.",
    primaryViews: ["Pipeline kanban", "Lead list", "Activity calendar", "Quotation/proposal tracker", "Forecast view"],
    recordFields: ["Lead", "Contact", "Company", "Need", "Budget/value", "Stage", "Probability", "Next activity", "Close risk"],
    primaryActions: ["Qualify", "Schedule call", "Send follow-up", "Draft proposal", "Create quote", "Move stage", "Mark lost/won"],
    automationMoments: ["New lead arrives", "No reply after follow-up", "Proposal sent", "Deal stalls", "High-value lead changes status"],
    approvalRules: ["Discounts require approval", "Custom terms require approval", "Final proposal send can require approval", "Do not reject valuable leads silently"],
    connectedApps: ["CRM", "Email", "Calendar", "Business phone", "SMS", "WhatsApp", "Payment links"],
    coworkerRoles: ["Lead qualifier", "Follow-up chaser", "Proposal drafter", "Pipeline analyst"],
    doneSignals: ["Next activity exists", "Stage and value updated", "Customer got the right follow-up", "Owner sees stalled/high-value deals"],
    operatingSurfaces: [
      { title: "Pipeline", description: "Lead stages, value, probability, and close risk." },
      { title: "Activities", description: "Calls, emails, meetings, next steps, and reminders." },
      { title: "Proposals", description: "Quotes, terms, objections, revisions, and approval." },
      { title: "Forecast", description: "Expected revenue, stalled deals, and conversion risk." },
    ],
    tabs: ["pipeline", "desk", "table", "doc", "calendar", "review"],
    manualTaskSeeds: ["Qualify hot lead", "Draft proposal follow-up", "Update deal stage", "Prepare objection response"],
    tableColumns: [
      { key: "item", label: "Opportunity", placeholder: "Lead or deal" },
      { key: "owner", label: "Contact", placeholder: "Decision maker" },
      { key: "status", label: "Stage", placeholder: "qualified, proposal, won" },
      { key: "next", label: "Next activity", placeholder: "Call, quote, follow-up" },
    ],
    pipelineStages: ["New", "Qualified", "Proposal", "Won"],
    artifactKinds: [
      { title: "Proposal", body: "Offer, scope, pricing notes, terms, and next step.", prompt: "Create a sales proposal from this department context.", kind: "document" },
      { title: "Follow-up sequence", body: "Email, SMS, and WhatsApp touches with timing.", prompt: "Draft a sales follow-up sequence.", kind: "message" },
      { title: "Pipeline report", body: "Deal values, stalled leads, and forecast notes.", prompt: "Create a sales pipeline report.", kind: "spreadsheet" },
    ],
    correctionFocus: "Correct lead fit, offer details, pricing boundaries, objections, urgency, and follow-up tone.",
    aiHandoffVerb: "move this opportunity forward",
  },
  marketing: {
    departmentId: "marketing",
    workObject: "campaign",
    headline: "Plan campaigns across content calendar, channels, briefs, publishing, and performance.",
    primaryViews: ["Campaign board", "Content calendar", "Channel list", "Asset tracker", "Performance dashboard"],
    recordFields: ["Campaign", "Audience", "Offer", "Channel", "Content type", "Publish date", "Status", "Metric", "Learning"],
    primaryActions: ["Plan campaign", "Draft content", "Repurpose", "Request design", "Schedule post", "Publish after approval", "Summarize performance"],
    automationMoments: ["New campaign brief", "Weekly content due", "Post approved", "Performance drops/spikes", "Comment or lead signal appears"],
    approvalRules: ["Public claims require approval", "Offers require approval", "Publishing can be gated", "Customer stories need consent"],
    connectedApps: ["Meta", "LinkedIn", "TikTok", "Canva", "Email marketing", "CRM", "Analytics"],
    coworkerRoles: ["Campaign planner", "Content writer", "Social publisher", "Performance analyst"],
    doneSignals: ["Campaign has assets", "Calendar has dates", "Approved posts are scheduled", "Performance learning is captured"],
    operatingSurfaces: [
      { title: "Campaigns", description: "Goals, audience, offer, angle, channel, and calendar." },
      { title: "Content calendar", description: "Posts, blogs, emails, captions, and publish dates." },
      { title: "Performance", description: "Engagement, leads, comments, tests, and next experiments." },
      { title: "Brand voice", description: "Claims, tone, examples, and forbidden messaging." },
    ],
    tabs: ["calendar", "board", "doc", "table", "assets", "review"],
    manualTaskSeeds: ["Plan next campaign", "Edit content calendar", "Review brand claim", "Prepare weekly posts"],
    tableColumns: [
      { key: "item", label: "Content", placeholder: "Post, email, blog, reel" },
      { key: "owner", label: "Channel", placeholder: "Instagram, email, blog" },
      { key: "status", label: "Status", placeholder: "idea, draft, approved" },
      { key: "next", label: "Publish step", placeholder: "Edit, design, approve, schedule" },
    ],
    pipelineStages: ["Idea", "Draft", "Design", "Scheduled"],
    artifactKinds: [
      { title: "Campaign brief", body: "Audience, offer, channels, message, and success metrics.", prompt: "Create a marketing campaign brief.", kind: "document" },
      { title: "Content calendar", body: "Planned posts with dates, owners, and channels.", prompt: "Create a marketing content calendar.", kind: "spreadsheet" },
      { title: "Creative package", body: "Captions, design prompts, and asset checklist.", prompt: "Create a creative package for this campaign.", kind: "design" },
    ],
    correctionFocus: "Correct audience, offer, claims, brand voice, content angle, and channel fit.",
    aiHandoffVerb: "prepare the next campaign asset",
  },
  creative: {
    departmentId: "creative",
    workObject: "asset",
    headline: "Produce designs, slides, videos, briefs, variants, and asset packages.",
    primaryViews: ["Asset board", "Creative brief", "Review rounds", "Deck workspace", "Video package", "Export checklist"],
    recordFields: ["Asset", "Format", "Objective", "Reference", "Copy", "Size", "Revision", "Approval", "Export need"],
    primaryActions: ["Write brief", "Create design", "Build deck", "Create variant", "Request feedback", "Package exports", "Send to marketing/sales"],
    automationMoments: ["Brief approved", "Revision requested", "Campaign needs assets", "Deck requested", "Export size missing"],
    approvalRules: ["Brand changes require approval", "Public-facing claims require approval", "Final export/publish requires approval", "Voice/image rights must be explicit"],
    connectedApps: ["Canva", "Figma", "Google Drive", "Media tools", "Brand kit", "Social platforms"],
    coworkerRoles: ["Creative director", "Design asset worker", "Presentation builder", "Video package worker"],
    doneSignals: ["Brief is clear", "Asset has required formats", "Feedback resolved", "Final package is ready for handoff"],
    operatingSurfaces: [
      { title: "Creative brief", description: "Objective, audience, references, brand rules, and constraints." },
      { title: "Asset board", description: "Designs, decks, videos, thumbnails, carousels, and variants." },
      { title: "Review rounds", description: "Feedback, changes, approvals, and final handoff." },
      { title: "Publishing handoff", description: "Export needs, captions, placements, and channel specs." },
    ],
    tabs: ["assets", "board", "doc", "table", "review"],
    manualTaskSeeds: ["Write creative brief", "Review slide structure", "Create design variants", "Package final assets"],
    tableColumns: [
      { key: "item", label: "Asset", placeholder: "Deck, poster, carousel, video" },
      { key: "owner", label: "Format", placeholder: "1080x1350, deck, reel" },
      { key: "status", label: "Review", placeholder: "draft, revision, approved" },
      { key: "next", label: "Creative note", placeholder: "Change color, layout, copy" },
    ],
    pipelineStages: ["Brief", "Production", "Revision", "Approved"],
    artifactKinds: [
      { title: "Editable design", body: "Posters, carousels, thumbnails, ads, and brand assets.", prompt: "Create editable design assets from this brief.", kind: "design" },
      { title: "Presentation deck", body: "Slide structure, copy, notes, and visuals.", prompt: "Create a presentation deck from this context.", kind: "design" },
      { title: "Video package", body: "Script, storyboard, voiceover notes, captions, and variants.", prompt: "Create a video package from this context.", kind: "video" },
    ],
    correctionFocus: "Correct layout direction, brand rules, reference style, copy, sizes, and export requirements.",
    aiHandoffVerb: "produce the next asset",
  },
  finance: {
    departmentId: "finance",
    workObject: "financial record",
    headline: "Work invoices, payments, reconciliation, collections, cash notes, and approval-only money actions.",
    primaryViews: ["Invoice list", "Payment matching", "Reconciliation table", "Cash risk brief", "Collections queue"],
    recordFields: ["Invoice", "Customer", "Amount", "Currency", "Due date", "Payment ref", "Status", "Mismatch reason", "Follow-up"],
    primaryActions: ["Create payment link", "Match payment", "Draft reminder", "Mark disputed", "Prepare cash brief", "Escalate overdue account"],
    automationMoments: ["Invoice overdue", "Payment received", "Payment mismatch", "Cash risk threshold crossed", "Customer disputes amount"],
    approvalRules: ["Money-impacting actions require approval", "Refunds require approval", "Penalty/discount requires approval", "Do not alter amounts automatically"],
    connectedApps: ["M-PESA", "Paystack", "Email", "SMS", "WhatsApp", "Accounting system", "Bank feed"],
    coworkerRoles: ["Invoice chaser", "Payment matcher", "Cash briefing analyst", "Receipt filing worker"],
    doneSignals: ["Payment status reconciled", "Reminder is approved or sent", "Mismatch is explained", "Owner sees cash risk"],
    operatingSurfaces: [
      { title: "Invoices", description: "Issued, overdue, disputed, paid, and follow-up status." },
      { title: "Payments", description: "M-PESA, Paystack, references, matching, and receipts." },
      { title: "Reconciliation", description: "Match payments to invoices and flag gaps." },
      { title: "Cash view", description: "Risks, expected cash, overdue value, and owner decisions." },
    ],
    tabs: ["table", "desk", "doc", "review"],
    manualTaskSeeds: ["Review overdue invoice", "Match payment reference", "Prepare collection note", "Flag finance risk"],
    tableColumns: [
      { key: "item", label: "Invoice/payment", placeholder: "Invoice or transaction" },
      { key: "owner", label: "Customer/source", placeholder: "Customer, M-PESA, Paystack" },
      { key: "status", label: "State", placeholder: "paid, overdue, mismatch" },
      { key: "next", label: "Finance action", placeholder: "Match, remind, dispute, approve" },
    ],
    pipelineStages: ["Issued", "Due", "Overdue", "Paid"],
    artifactKinds: [
      { title: "Cash brief", body: "Overdue value, risks, expected payments, and owner decisions.", prompt: "Create a cash risk brief from this finance context.", kind: "document" },
      { title: "Reconciliation sheet", body: "Payments, references, invoices, status, and mismatches.", prompt: "Create a reconciliation tracker.", kind: "spreadsheet" },
      { title: "Payment reminder", body: "Respectful collection message that stays approval-gated.", prompt: "Draft a payment reminder for approval.", kind: "payment" },
    ],
    correctionFocus: "Correct amounts, invoice IDs, payment references, customer tone, and money-action approval boundaries.",
    aiHandoffVerb: "prepare the finance action for approval",
  },
  engineering: {
    departmentId: "engineering",
    workObject: "issue",
    headline: "Work product feedback into issues, specs, sprints, QA, releases, docs, and engineering handoffs.",
    primaryViews: ["Backlog", "Sprint board", "Bug triage", "QA checklist", "Release notes", "Product feedback inbox"],
    recordFields: ["Issue", "Type", "Evidence", "Priority", "Complexity", "Owner", "Acceptance criteria", "Release", "Risk"],
    primaryActions: ["Create issue", "Write spec", "Add repro steps", "Draft QA plan", "Prepare release notes", "Escalate blocker"],
    automationMoments: ["Support case becomes bug", "Release window starts", "QA fails", "Customer repeats same issue", "GitHub/Linear status changes"],
    approvalRules: ["Code changes require approval", "Deployments require approval", "Security issues escalate", "Do not expose secrets or private repo content"],
    connectedApps: ["GitHub", "Linear", "Jira", "Figma", "Docs", "Sentry", "Vercel/Cloud logs"],
    coworkerRoles: ["Product triage agent", "Issue packager", "QA/release worker", "Technical docs worker"],
    doneSignals: ["Issue has evidence", "Acceptance criteria are clear", "QA risk is visible", "Release note or handoff is ready"],
    operatingSurfaces: [
      { title: "Backlog", description: "Bugs, feature requests, ideas, and customer evidence." },
      { title: "Sprints", description: "Priority, complexity, owner, due date, and release target." },
      { title: "QA", description: "Reproduction steps, test cases, rollout risks, and acceptance criteria." },
      { title: "Release", description: "Release notes, blockers, deploy approval, and docs." },
    ],
    tabs: ["pipeline", "board", "doc", "table", "review"],
    manualTaskSeeds: ["Package customer bug", "Draft release note", "Write acceptance criteria", "Prepare QA checklist"],
    tableColumns: [
      { key: "item", label: "Issue/spec", placeholder: "Bug, feature, release item" },
      { key: "owner", label: "Owner", placeholder: "Engineer, product, QA" },
      { key: "status", label: "Stage", placeholder: "triage, ready, testing" },
      { key: "next", label: "Technical next step", placeholder: "Repro, spec, test, release" },
    ],
    pipelineStages: ["Triage", "Ready", "In build", "QA"],
    artifactKinds: [
      { title: "Issue package", body: "Problem, evidence, repro steps, acceptance criteria, and owner.", prompt: "Create an engineering issue package.", kind: "code" },
      { title: "QA checklist", body: "Test cases, risks, environments, and pass/fail notes.", prompt: "Create a QA checklist.", kind: "document" },
      { title: "Release notes", body: "User-facing summary, technical notes, and rollout risks.", prompt: "Draft release notes from this context.", kind: "document" },
    ],
    correctionFocus: "Correct reproduction steps, acceptance criteria, product scope, technical risk, and deploy approval rules.",
    aiHandoffVerb: "package the next engineering action",
  },
  support: {
    departmentId: "support",
    workObject: "support case",
    headline: "Resolve tickets with case queues, knowledge answers, complaint recovery, and escalation controls.",
    primaryViews: ["Ticket queue", "Customer timeline", "Knowledge base", "Complaint/recovery queue", "SLA risk view"],
    recordFields: ["Case", "Customer", "Issue", "Sentiment", "Priority", "Policy", "Next reply", "Escalation reason", "Resolution"],
    primaryActions: ["Answer", "Create ticket", "Classify", "Update knowledge", "Draft recovery response", "Escalate refund/complaint"],
    automationMoments: ["New ticket", "Negative sentiment", "SLA almost breached", "Repeated question", "Refund or complaint keyword appears"],
    approvalRules: ["Refunds require approval", "Liability language requires approval", "Angry/high-value customers escalate", "No invented policies"],
    connectedApps: ["WhatsApp", "Email", "Website chat", "CRM", "Zendesk/Freshdesk", "Knowledge base"],
    coworkerRoles: ["FAQ responder", "Ticket triage worker", "Recovery response agent", "Knowledge updater"],
    doneSignals: ["Customer has a clear answer", "Ticket state updated", "Sensitive case escalated", "Knowledge gap captured"],
    operatingSurfaces: [
      { title: "Case queue", description: "Open tickets, urgency, sentiment, owner, and customer history." },
      { title: "Knowledge", description: "Approved answers, policies, troubleshooting steps, and gaps." },
      { title: "Recovery", description: "Complaints, refunds, apology drafts, and trust-sensitive cases." },
      { title: "Escalation", description: "Human handoff, SLA risk, VIP customers, and unclear policy." },
    ],
    tabs: ["desk", "pipeline", "doc", "table", "review"],
    manualTaskSeeds: ["Triage open complaint", "Edit FAQ answer", "Prepare recovery response", "Flag refund request"],
    tableColumns: [
      { key: "item", label: "Case", placeholder: "Ticket or customer issue" },
      { key: "owner", label: "Customer", placeholder: "Customer or account" },
      { key: "status", label: "Status", placeholder: "open, waiting, resolved" },
      { key: "next", label: "Resolution step", placeholder: "Reply, escalate, update FAQ" },
    ],
    pipelineStages: ["New", "Investigating", "Waiting", "Resolved"],
    artifactKinds: [
      { title: "Support reply", body: "Careful customer response with policy-safe language.", prompt: "Draft a support response from this case context.", kind: "message" },
      { title: "Knowledge article", body: "Reusable FAQ or troubleshooting guide.", prompt: "Create a knowledge-base article from this support context.", kind: "document" },
      { title: "Recovery plan", body: "Complaint summary, risk, proposed response, and escalation.", prompt: "Create a customer recovery plan.", kind: "document" },
    ],
    correctionFocus: "Correct customer facts, policy language, empathy, refund boundaries, and escalation urgency.",
    aiHandoffVerb: "prepare the next support resolution",
  },
  operations: {
    departmentId: "operations",
    workObject: "operations item",
    headline: "Coordinate orders, suppliers, blockers, inventory, fulfillment, and internal handoffs.",
    primaryViews: ["Operations board", "Supplier tracker", "Fulfillment table", "Inventory/checklist view", "Blocker queue"],
    recordFields: ["Item", "Supplier/owner", "Due date", "Dependency", "Blocker", "Customer impact", "Status", "Next action"],
    primaryActions: ["Create task", "Chase supplier", "Update fulfillment", "Log blocker", "Prepare customer update", "Escalate delay"],
    automationMoments: ["Supplier misses update", "Order delayed", "Inventory threshold hit", "Task blocked", "Customer-impacting delay appears"],
    approvalRules: ["Purchase changes require approval", "Customer commitments require approval", "Supplier cancellations require approval", "No blame-heavy messages"],
    connectedApps: ["Email", "Calendar", "Task/project tools", "Inventory/order systems", "CRM", "WhatsApp"],
    coworkerRoles: ["Task coordinator", "Supplier follow-up worker", "Operations briefer", "Blocker escalation worker"],
    doneSignals: ["Owner and next action clear", "Supplier/customer updated", "Blocker has escalation path", "Record status changed"],
    operatingSurfaces: [
      { title: "Fulfillment", description: "Orders, delivery status, delays, and customer-impacting blockers." },
      { title: "Suppliers", description: "Vendor follow-ups, commitments, lead times, and issues." },
      { title: "Processes", description: "SOPs, checklists, recurring tasks, and exceptions." },
      { title: "Handoffs", description: "What moves to projects, support, finance, or the owner." },
    ],
    tabs: ["board", "table", "doc", "calendar", "review"],
    manualTaskSeeds: ["Clear supplier blocker", "Update fulfillment tracker", "Prepare customer update", "Review recurring SOP"],
    tableColumns: [
      { key: "item", label: "Operation", placeholder: "Order, supplier, process" },
      { key: "owner", label: "Owner", placeholder: "Team, supplier, partner" },
      { key: "status", label: "State", placeholder: "blocked, waiting, done" },
      { key: "next", label: "Next step", placeholder: "Chase, update, escalate" },
    ],
    pipelineStages: ["Open", "Waiting", "Blocked", "Complete"],
    artifactKinds: [
      { title: "SOP", body: "Step-by-step process that can be reused.", prompt: "Create an operations SOP from this context.", kind: "document" },
      { title: "Supplier follow-up", body: "Polite, specific vendor update request.", prompt: "Draft a supplier follow-up.", kind: "message" },
      { title: "Ops tracker", body: "Owners, blockers, dates, and next actions.", prompt: "Create an operations tracker.", kind: "spreadsheet" },
    ],
    correctionFocus: "Correct owners, deadlines, supplier commitments, customer impact, and irreversible operations decisions.",
    aiHandoffVerb: "coordinate the next operations move",
  },
  admin: {
    departmentId: "admin",
    workObject: "admin task",
    headline: "Manage calendars, reminders, documents, internal requests, and recurring back-office work.",
    primaryViews: ["Calendar", "Reminder list", "Document cabinet", "Request queue", "Recurring admin checklist"],
    recordFields: ["Request", "Person", "Date/time", "Document", "Priority", "Privacy level", "Status", "Next step"],
    primaryActions: ["Schedule", "Reschedule", "Send reminder", "File document", "Summarize note", "Prepare meeting brief"],
    automationMoments: ["Meeting approaching", "Document received", "Recurring reminder due", "Calendar conflict detected", "Internal request created"],
    approvalRules: ["Private calendar changes can require approval", "Sensitive documents stay restricted", "Do not delete important records", "Personnel/legal admin escalates"],
    connectedApps: ["Google Calendar", "Gmail", "Google Drive", "Docs", "Slack/Teams", "Notion"],
    coworkerRoles: ["Calendar worker", "Document filing worker", "Admin follow-through worker", "Meeting prep assistant"],
    doneSignals: ["Calendar updated", "Reminder sent or queued", "Document filed", "Meeting has prep and follow-up"],
    operatingSurfaces: [
      { title: "Calendar", description: "Meetings, bookings, reminders, conflicts, and preparation." },
      { title: "Documents", description: "Files, forms, summaries, letters, and organized records." },
      { title: "Requests", description: "Internal admin asks, confirmations, and recurring follow-up." },
      { title: "Routine loops", description: "Daily, weekly, and monthly office maintenance." },
    ],
    tabs: ["calendar", "desk", "doc", "table", "review"],
    manualTaskSeeds: ["Resolve calendar conflict", "File document", "Prepare meeting note", "Send internal reminder"],
    tableColumns: [
      { key: "item", label: "Admin item", placeholder: "Meeting, document, reminder" },
      { key: "owner", label: "Person", placeholder: "Owner or attendee" },
      { key: "status", label: "Status", placeholder: "pending, sent, filed" },
      { key: "next", label: "Admin step", placeholder: "Book, remind, file, summarize" },
    ],
    pipelineStages: ["Requested", "Scheduled", "Waiting", "Done"],
    artifactKinds: [
      { title: "Meeting brief", body: "Agenda, context, attendees, questions, and follow-ups.", prompt: "Create a meeting brief from this admin context.", kind: "document" },
      { title: "Reminder pack", body: "Polite reminders and timing plan.", prompt: "Create an admin reminder pack.", kind: "message" },
      { title: "Document summary", body: "Summarize and file important records.", prompt: "Create a document summary.", kind: "document" },
    ],
    correctionFocus: "Correct dates, participants, privacy, internal tone, and what must not be moved automatically.",
    aiHandoffVerb: "complete the next admin step",
  },
  projects: {
    departmentId: "projects",
    workObject: "deliverable",
    headline: "Run deliverables through scope, milestones, dependencies, approvals, and handoff.",
    primaryViews: ["Project board", "Timeline", "Deliverable list", "Dependency map", "Approval queue", "Client handoff"],
    recordFields: ["Deliverable", "Owner", "Client/stakeholder", "Due date", "Dependency", "Scope", "Status", "Acceptance criteria"],
    primaryActions: ["Create milestone", "Assign task", "Package deliverable", "Chase approval", "Update timeline", "Prepare handoff"],
    automationMoments: ["Deadline approaching", "Approval stalls", "Dependency blocked", "Deliverable ready", "Scope change requested"],
    approvalRules: ["Scope changes require approval", "Client delivery requires approval", "Pricing/timeline commitments require approval", "Acceptance criteria must be explicit"],
    connectedApps: ["Project tool", "Email", "Calendar", "Docs", "Drive", "Slack/Teams", "Canva/Figma"],
    coworkerRoles: ["Project orchestrator", "Deliverable packager", "Approval chaser", "Client handoff worker"],
    doneSignals: ["Deliverable has owner/date", "Blockers visible", "Approval captured", "Handoff package ready"],
    operatingSurfaces: [
      { title: "Timeline", description: "Milestones, deadlines, dependencies, and scope changes." },
      { title: "Deliverables", description: "Client work, internal packages, files, and acceptance criteria." },
      { title: "Approvals", description: "Stakeholder reviews, owner decisions, and waiting blockers." },
      { title: "Handoff", description: "What moves to sales, support, operations, or creative." },
    ],
    tabs: ["board", "table", "doc", "calendar", "review"],
    manualTaskSeeds: ["Update delivery timeline", "Package deliverable", "Chase approval", "Clarify project scope"],
    tableColumns: [
      { key: "item", label: "Deliverable", placeholder: "Deliverable or milestone" },
      { key: "owner", label: "Owner", placeholder: "Owner or stakeholder" },
      { key: "status", label: "Status", placeholder: "planned, blocked, review" },
      { key: "next", label: "Next move", placeholder: "Build, review, send, approve" },
    ],
    pipelineStages: ["Planned", "In progress", "Review", "Delivered"],
    artifactKinds: [
      { title: "Project brief", body: "Scope, owners, milestones, risks, and acceptance criteria.", prompt: "Create a project brief from this context.", kind: "document" },
      { title: "Delivery tracker", body: "Timeline, owners, status, blockers, and due dates.", prompt: "Create a project delivery tracker.", kind: "spreadsheet" },
      { title: "Client handoff", body: "Delivery message, summary, attachments, and next step.", prompt: "Draft a client handoff package.", kind: "document" },
    ],
    correctionFocus: "Correct scope, stakeholder commitments, due dates, acceptance criteria, and approval authority.",
    aiHandoffVerb: "move the deliverable forward",
  },
  hr: {
    departmentId: "hr",
    workObject: "people task",
    headline: "Coordinate onboarding, leave, team requests, policies, and people operations carefully.",
    primaryViews: ["Onboarding checklist", "People request queue", "Policy acknowledgements", "Leave/calendar view", "Confidential escalation"],
    recordFields: ["Person", "Request", "Manager", "Due date", "Document", "Policy", "Sensitivity", "Status", "Next step"],
    primaryActions: ["Send onboarding step", "Schedule check-in", "Request acknowledgement", "Draft people note", "Escalate sensitive case"],
    automationMoments: ["New hire added", "Policy acknowledgement due", "Leave request received", "Manager check-in due", "Sensitive phrase detected"],
    approvalRules: ["Hiring/firing/payroll decisions are human-only", "Confidential records restricted", "Sensitive people messages require approval", "Policy changes require approval"],
    connectedApps: ["Email", "Calendar", "Docs", "HRIS", "Slack/Teams", "Drive"],
    coworkerRoles: ["Onboarding worker", "People ops reminder", "Policy acknowledgement worker", "Manager follow-up assistant"],
    doneSignals: ["Checklist advanced", "Person notified", "Sensitive item escalated", "Policy/audit record updated"],
    operatingSurfaces: [
      { title: "Onboarding", description: "Checklists, documents, meetings, equipment, and first-week flow." },
      { title: "People requests", description: "Leave, internal requests, acknowledgements, and reminders." },
      { title: "Policies", description: "Policy reads, confirmations, and HR-safe language." },
      { title: "Confidentiality", description: "Sensitive cases that must stay human-only." },
    ],
    tabs: ["desk", "calendar", "doc", "table", "review"],
    manualTaskSeeds: ["Review onboarding checklist", "Prepare policy acknowledgement", "Schedule check-in", "Flag confidential issue"],
    tableColumns: [
      { key: "item", label: "People item", placeholder: "Onboarding, leave, policy" },
      { key: "owner", label: "Person", placeholder: "Employee or manager" },
      { key: "status", label: "Status", placeholder: "pending, acknowledged" },
      { key: "next", label: "People step", placeholder: "Schedule, remind, escalate" },
    ],
    pipelineStages: ["Requested", "In progress", "Waiting", "Closed"],
    artifactKinds: [
      { title: "Onboarding plan", body: "Steps, owners, due dates, and first-week checklist.", prompt: "Create an onboarding plan.", kind: "document" },
      { title: "Policy note", body: "Clear internal policy acknowledgement message.", prompt: "Draft a policy acknowledgement note.", kind: "message" },
      { title: "People tracker", body: "Requests, owners, due dates, and status.", prompt: "Create a people-ops tracker.", kind: "spreadsheet" },
    ],
    correctionFocus: "Correct names, dates, sensitivity level, policy wording, confidentiality, and human-only decisions.",
    aiHandoffVerb: "prepare the next people-ops step",
  },
  growth: {
    departmentId: "growth",
    workObject: "experiment",
    headline: "Discover opportunities, run experiments, track channels, and turn signals into growth moves.",
    primaryViews: ["Opportunity radar", "Experiment board", "Partner pipeline", "Competitor watch", "Learning log"],
    recordFields: ["Opportunity", "Source", "Hypothesis", "Channel", "Metric", "Confidence", "Status", "Next test"],
    primaryActions: ["Research", "Score", "Draft experiment", "Create outreach", "Measure result", "Recommend next test"],
    automationMoments: ["Competitor changes", "Campaign spike", "Lead source changes", "Experiment reaches date", "Partner opportunity found"],
    approvalRules: ["Spend requires approval", "Pricing changes require approval", "Partner commitments require approval", "External outreach can be gated"],
    connectedApps: ["CRM", "Analytics", "Social platforms", "Email", "Research tools", "Ads accounts", "Docs"],
    coworkerRoles: ["Opportunity scout", "Experiment operator", "Partnership researcher", "Growth analyst"],
    doneSignals: ["Opportunity has evidence", "Experiment has metric/date", "Learning captured", "Next test is clear"],
    operatingSurfaces: [
      { title: "Opportunity radar", description: "Markets, competitors, partners, channels, and customer signals." },
      { title: "Experiments", description: "Hypotheses, variants, owners, dates, and measurements." },
      { title: "Partnerships", description: "Targets, fit, outreach, terms, and owner decisions." },
      { title: "Learning", description: "Results, next test, stop/continue decisions, and evidence." },
    ],
    tabs: ["pipeline", "board", "doc", "table", "review"],
    manualTaskSeeds: ["Research opportunity", "Draft experiment", "Score partner fit", "Review growth signal"],
    tableColumns: [
      { key: "item", label: "Opportunity", placeholder: "Experiment, partner, channel" },
      { key: "owner", label: "Signal/source", placeholder: "Source or owner" },
      { key: "status", label: "Stage", placeholder: "research, testing, learned" },
      { key: "next", label: "Next test", placeholder: "Research, launch, measure" },
    ],
    pipelineStages: ["Found", "Scored", "Testing", "Learned"],
    artifactKinds: [
      { title: "Experiment brief", body: "Hypothesis, audience, channel, metric, and run plan.", prompt: "Create a growth experiment brief.", kind: "document" },
      { title: "Partner list", body: "Targets, fit score, evidence, and outreach notes.", prompt: "Create a partnership prospect tracker.", kind: "spreadsheet" },
      { title: "Opportunity report", body: "Market signal, competitor pattern, risk, and next move.", prompt: "Create a growth opportunity report.", kind: "document" },
    ],
    correctionFocus: "Correct evidence, assumptions, channel fit, test size, spend limits, and partnership authority.",
    aiHandoffVerb: "prepare the next growth experiment",
  },
  analytics: {
    departmentId: "analytics",
    workObject: "signal",
    headline: "Turn metrics, anomalies, reports, and business events into decisions worth making.",
    primaryViews: ["KPI dashboard", "Signal feed", "Anomaly queue", "Report builder", "Board metrics"],
    recordFields: ["Metric", "Source", "Time range", "Baseline", "Movement", "Confidence", "Interpretation", "Next check"],
    primaryActions: ["Explain metric", "Create report", "Build tracker", "Flag anomaly", "Compare period", "Prepare board note"],
    automationMoments: ["Metric crosses threshold", "Daily/weekly report due", "Anomaly detected", "Source sync updates", "Board report requested"],
    approvalRules: ["Do not invent missing data", "Low confidence must be labelled", "Strategic conclusions need evidence", "Source changes are logged"],
    connectedApps: ["Sheets", "CRM", "Paystack/M-PESA", "Analytics", "Database", "Docs", "BI tools"],
    coworkerRoles: ["Signal watcher", "Briefing generator", "Anomaly explainer", "Board metric analyst"],
    doneSignals: ["Metric source clear", "Explanation has confidence", "Next check defined", "Report is readable"],
    operatingSurfaces: [
      { title: "Signals", description: "Metric changes, anomalies, alerts, and explanations." },
      { title: "Reports", description: "Daily, weekly, monthly, and board-ready summaries." },
      { title: "Dashboards", description: "KPIs, trend lines, segments, and watchlists." },
      { title: "Questions", description: "Business questions, hypotheses, and evidence trails." },
    ],
    tabs: ["table", "doc", "board", "review"],
    manualTaskSeeds: ["Explain metric movement", "Build weekly report", "Investigate anomaly", "Prepare board metric"],
    tableColumns: [
      { key: "item", label: "Metric/signal", placeholder: "Revenue, leads, churn, engagement" },
      { key: "owner", label: "Source", placeholder: "CRM, finance, website, sheet" },
      { key: "status", label: "Meaning", placeholder: "normal, anomaly, risk" },
      { key: "next", label: "Check next", placeholder: "Compare, explain, escalate" },
    ],
    pipelineStages: ["Detected", "Explaining", "Decision", "Archived"],
    artifactKinds: [
      { title: "KPI report", body: "Metrics, interpretation, trend, and next action.", prompt: "Create a KPI report from this analytics context.", kind: "document" },
      { title: "Dashboard table", body: "Metric, source, baseline, movement, and owner.", prompt: "Create a dashboard tracker.", kind: "spreadsheet" },
      { title: "Anomaly brief", body: "What changed, possible causes, confidence, and checks.", prompt: "Create an anomaly explanation brief.", kind: "document" },
    ],
    correctionFocus: "Correct metric definitions, source data, time range, confidence, and interpretation.",
    aiHandoffVerb: "explain the next signal",
  },
  compliance: {
    departmentId: "compliance",
    workObject: "risk item",
    headline: "Watch consent, policies, approvals, audit trails, privacy, and high-risk exceptions.",
    primaryViews: ["Risk register", "Policy exceptions", "Consent log", "Approval audit", "Sensitive action queue"],
    recordFields: ["Risk", "Policy", "Department", "Owner", "Evidence", "Severity", "Control", "Decision", "Audit note"],
    primaryActions: ["Log risk", "Check consent", "Request approval", "Prepare audit note", "Block risky action", "Escalate"],
    automationMoments: ["High-risk action proposed", "Missing consent", "Approval bypass attempted", "Integration fails", "Sensitive data detected"],
    approvalRules: ["Legal interpretations escalate", "Consent cannot be invented", "High-risk actions pause", "Audit trail must be preserved"],
    connectedApps: ["Approvals", "CRM", "Email", "Docs", "Audit logs", "Security tools"],
    coworkerRoles: ["Policy guard", "Consent auditor", "Risk escalation agent", "Audit note worker"],
    doneSignals: ["Risk is logged", "Control is assigned", "Approval trail exists", "Sensitive action is blocked or escalated"],
    operatingSurfaces: [
      { title: "Policy checks", description: "Rules, exceptions, owner decisions, and controls." },
      { title: "Consent", description: "Outreach permission, customer data, and communication boundaries." },
      { title: "Audit trail", description: "Who approved what, when, and why." },
      { title: "Risk review", description: "High-risk actions, sensitive data, and escalation." },
    ],
    tabs: ["table", "doc", "desk", "review"],
    manualTaskSeeds: ["Review policy exception", "Check consent evidence", "Prepare audit note", "Escalate high-risk action"],
    tableColumns: [
      { key: "item", label: "Risk item", placeholder: "Policy, consent, approval, data issue" },
      { key: "owner", label: "Owner/source", placeholder: "Department or owner" },
      { key: "status", label: "Risk state", placeholder: "open, reviewed, escalated" },
      { key: "next", label: "Control", placeholder: "Log, approve, block, escalate" },
    ],
    pipelineStages: ["Open", "Reviewing", "Escalated", "Closed"],
    artifactKinds: [
      { title: "Audit note", body: "Event, evidence, owner, risk, and decision trail.", prompt: "Create an audit note from this context.", kind: "document" },
      { title: "Policy checklist", body: "Rules, exceptions, required approvals, and control points.", prompt: "Create a policy checklist.", kind: "document" },
      { title: "Risk register", body: "Risks, severity, owner, control, and status.", prompt: "Create a risk register.", kind: "spreadsheet" },
    ],
    correctionFocus: "Correct risk level, policy interpretation, consent evidence, audit wording, and legal-sensitive boundaries.",
    aiHandoffVerb: "prepare the next compliance review",
  },
};

export function getDepartmentWorkspaceProfile(departmentId: OfficeDepartmentId): DepartmentWorkspaceProfile {
  return DEPARTMENT_WORKSPACE_PROFILES[departmentId] ?? {
    ...fallbackProfile,
    departmentId,
  };
}
