import Anthropic from "@anthropic-ai/sdk";
import fs from "fs/promises";
import path from "path";
import type { ConnectorExecutor } from "@/lib/connectors/sdk";

const anthropic = process.env.ANTHROPIC_API_KEY
  ? new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
  : null;

function fallbackDocument(context: Parameters<ConnectorExecutor["execute"]>[0]) {
  const sections = Object.entries(context.stepOutputs).map(([stepId, output]) => ({
    stepId,
    output,
  }));

  const markdown = [
    `# ${context.workflow.title}`,
    "",
    `Generated by Dobly Orchestrator at ${new Date().toISOString()}.`,
    "",
    "## Trigger Payload",
    "```json",
    JSON.stringify(context.triggerPayload, null, 2),
    "```",
    "",
    "## Step Outputs",
    ...sections.flatMap((section) => [
      `### ${section.stepId}`,
      "```json",
      JSON.stringify(section.output, null, 2),
      "```",
      "",
    ]),
  ].join("\n");

  return {
    markdown,
    subject: `${context.workflow.title} report`,
    text: markdown,
    json: {
      workflow: context.workflow.title,
      triggerPayload: context.triggerPayload,
      steps: sections,
    },
  };
}

function escapeHtml(input: string) {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function markdownToHtml(markdown: string) {
  return [
    "<!doctype html>",
    '<html lang="en">',
    "  <head>",
    '    <meta charset="utf-8" />',
    `    <title>Dobly Report</title>`,
    "    <style>body{font-family:Arial,sans-serif;line-height:1.6;padding:32px;max-width:960px;margin:0 auto;background:#f7f8f5;color:#091210} pre{background:#eef2ef;padding:16px;border-radius:12px;overflow:auto} code{font-family:'Courier New',monospace}</style>",
    "  </head>",
    "  <body>",
    `    <pre>${escapeHtml(markdown)}</pre>`,
    "  </body>",
    "</html>",
  ].join("\n");
}

function escapePdfText(input: string) {
  return input.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function buildSimplePdf(text: string) {
  const lines = text
    .replace(/\r\n/g, "\n")
    .split("\n")
    .flatMap((line) => {
      if (line.length <= 90) return [line];
      const chunks = [];
      for (let index = 0; index < line.length; index += 90) {
        chunks.push(line.slice(index, index + 90));
      }
      return chunks;
    })
    .slice(0, 200);

  const contentLines = [
    "BT",
    "/F1 11 Tf",
    "50 780 Td",
    "14 TL",
    ...lines.map((line, index) =>
      `${index === 0 ? "" : "T* " }(${escapePdfText(line)}) Tj`.trim()
    ),
    "ET",
  ];
  const contentStream = contentLines.join("\n");
  const objects = [
    "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj",
    "2 0 obj\n<< /Type /Pages /Count 1 /Kids [3 0 R] >>\nendobj",
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj",
    "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj",
    `5 0 obj\n<< /Length ${Buffer.byteLength(contentStream, "utf8")} >>\nstream\n${contentStream}\nendstream\nendobj`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];

  for (const object of objects) {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${object}\n`;
  }

  const xrefStart = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";

  for (let index = 1; index < offsets.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, "0")} 00000 n \n`;
  }

  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;
  return Buffer.from(pdf, "utf8");
}

function sanitizePathPart(input: string) {
  return input.replace(/[<>:"|?*]+/g, "-").replace(/\\/g, "/").trim();
}

function resolveSafeOutputBase(input: string, workflowId: string) {
  const cwd = process.cwd();
  const fallback = path.join("outputs", "reports", workflowId, `run-${Date.now()}`, "report");
  const requested = sanitizePathPart(input || fallback);
  const resolved = path.resolve(cwd, requested);

  if (!resolved.startsWith(cwd)) {
    throw new Error("Orchestrator artifacts must stay inside the Dobly workspace.");
  }

  return resolved;
}

async function writeArtifacts(
  basePath: string,
  content: { markdown: string; text: string; json: Record<string, unknown> }
) {
  const markdownPath = `${basePath}.md`;
  const jsonPath = `${basePath}.json`;
  const htmlPath = `${basePath}.html`;
  const pdfPath = `${basePath}.pdf`;

  await fs.mkdir(path.dirname(markdownPath), { recursive: true });
  await Promise.all([
    fs.writeFile(markdownPath, content.markdown, "utf8"),
    fs.writeFile(jsonPath, JSON.stringify(content.json, null, 2), "utf8"),
    fs.writeFile(htmlPath, markdownToHtml(content.markdown), "utf8"),
    fs.writeFile(pdfPath, buildSimplePdf(content.text)),
  ]);

  return { markdownPath, jsonPath, htmlPath, pdfPath };
}

export const orchestratorDocumentExecutor: ConnectorExecutor = {
  id: "native.dobly.orchestrator.document",
  async execute(context) {
    const assembled = fallbackDocument(context);
    const prompt = String(
      context.config.prompt ??
        "Create a concise operations report using the provided trigger and step outputs. Return markdown only."
    );

    let markdown = assembled.markdown;
    if (!anthropic) {
      const artifacts =
        context.config.writeArtifacts === false
          ? null
          : await writeArtifacts(
              resolveSafeOutputBase(
                String(context.config.artifactBasePath ?? ""),
                context.workflow.id
              ),
              assembled
            );

      return {
        ...assembled,
        artifacts,
        artifactBasePath: artifacts?.markdownPath?.replace(/\.md$/, "") ?? null,
      };
    }

    try {
      const message = await anthropic.messages.create({
        model: "claude-sonnet-4-20250514",
        max_tokens: 1600,
        system:
          "You are Dobly Orchestrator. You turn collected workflow outputs into clean human-readable reports.",
        messages: [
          {
            role: "user",
            content: `${prompt}\n\nTrigger:\n${JSON.stringify(
              context.triggerPayload,
              null,
              2
            )}\n\nOutputs:\n${JSON.stringify(context.stepOutputs, null, 2)}`,
          },
        ],
      });

      const content = message.content[0];
      if (content && content.type === "text") {
        markdown = content.text;
      }
    } catch {
      markdown = assembled.markdown;
    }

    const enriched = {
      markdown,
      subject: `${context.workflow.title} report`,
      text: markdown,
      json: {
        ...assembled.json,
        prompt,
      },
    };

    const artifacts =
      context.config.writeArtifacts === false
        ? null
        : await writeArtifacts(
            resolveSafeOutputBase(
              String(context.config.artifactBasePath ?? ""),
              context.workflow.id
            ),
            enriched
          );

    return {
      ...enriched,
      artifacts,
      artifactBasePath: artifacts?.markdownPath?.replace(/\.md$/, "") ?? null,
    };
  },
};
