import "server-only";
import { inferCapabilitiesFromText, type DoblyCapability } from "@/lib/runtime/capabilities";

export type ConnectorKind = "oauth" | "mcp" | "custom_api" | "local_bridge" | "native";
export type ConnectorCategory =
  | "design"
  | "engineering"
  | "code"
  | "documents"
  | "commerce"
  | "communication"
  | "social"
  | "finance"
  | "crm"
  | "media"
  | "data"
  | "browser"
  | "personal"
  | "custom";

export type ConnectorRisk = "low" | "medium" | "high";

export interface UniversalConnectorActionPolicy {
  action: string;
  description: string;
  riskLevel: ConnectorRisk;
  approvalRequired: boolean;
  rollbackSupport: "automatic" | "manual" | "versioned_artifact" | "not_available";
}

export interface UniversalConnectorDefinition {
  id: string;
  label: string;
  provider: string;
  kind: ConnectorKind;
  category: ConnectorCategory;
  description: string;
  whatItEnables: string[];
  examplePrompts: string[];
  setupSteps: string[];
  requiredUserInputs: Array<{
    key: string;
    label: string;
    type: "url" | "token" | "text" | "oauth" | "local_command" | "file";
    required: boolean;
    help: string;
  }>;
  capabilities: DoblyCapability[];
  defaultRisk: ConnectorRisk;
  approvalPolicies: UniversalConnectorActionPolicy[];
  permissionScopes: string[];
  sandbox: {
    available: boolean;
    defaultMode: "read_only" | "draft_only" | "approval_required" | "live";
    notes: string;
  };
  localBridge?: {
    required: boolean;
    name: string;
    installHint: string;
    healthPath?: string;
  };
  artifactSupport: Array<"image" | "video" | "audio" | "document" | "spreadsheet" | "cad" | "json" | "external_link">;
  rollbackSupport: "automatic" | "manual" | "versioned_artifact" | "not_available";
}

function caps(text: string): DoblyCapability[] {
  return inferCapabilitiesFromText(text) as DoblyCapability[];
}

interface StandbyConnectorSeed {
  id: string;
  label: string;
  provider: string;
  kind?: ConnectorKind;
  category: ConnectorCategory;
  description: string;
  enables: string[];
  prompts: string[];
  capabilityText: string;
  risk?: ConnectorRisk;
  scopes: string[];
  artifacts?: UniversalConnectorDefinition["artifactSupport"];
  rollback?: UniversalConnectorDefinition["rollbackSupport"];
  setupNoun?: string;
}

function standbyConnector(seed: StandbyConnectorSeed): UniversalConnectorDefinition {
  const kind = seed.kind ?? "oauth";
  const defaultRisk = seed.risk ?? "high";
  const label = seed.label;
  const setupNoun = seed.setupNoun ?? `${label} account`;
  const isLocalBridge = kind === "local_bridge";
  const isCustom = kind === "custom_api";
  const requiredUserInputs = isLocalBridge
    ? [
        { key: "serverUrl", label: `${label} local bridge URL`, type: "url" as const, required: true, help: "Local bridge endpoint running on this device or network." },
        { key: "authToken", label: "Auth token", type: "token" as const, required: false, help: "Optional token for the connector server." },
      ]
    : isCustom
    ? [
        { key: "baseUrl", label: `${label} bridge/API URL`, type: "url" as const, required: true, help: "Secure bridge or API endpoint Dobly should call." },
        { key: "authSecret", label: "Auth secret", type: "token" as const, required: false, help: "Token or secret for this connector." },
      ]
    : [{ key: "oauth", label: setupNoun, type: "oauth" as const, required: true, help: `Connect ${setupNoun}.` }];

  return {
    id: seed.id,
    label,
    provider: seed.provider,
    kind,
    category: seed.category,
    description: seed.description,
    whatItEnables: seed.enables,
    examplePrompts: seed.prompts,
    setupSteps: [
      `Connect ${setupNoun}.`,
      "Choose the workspace, project, account, or data scope Operators may access.",
      "Set approval rules for risky reads, writes, external messages, money movement, or production changes.",
      "Run Test Connection and review discovered actions before assigning it to Operators.",
    ],
    requiredUserInputs,
    capabilities: caps(seed.capabilityText),
    defaultRisk,
    approvalPolicies: [
      { action: "read_context", description: `Read approved ${label} context.`, riskLevel: defaultRisk === "low" ? "low" : "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "prepare_change", description: "Prepare drafts, reports, actions, or changes as reviewable artifacts.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "versioned_artifact" },
      { action: "apply_or_execute", description: "Apply changes, publish externally, trigger production actions, or move money.", riskLevel: "high", approvalRequired: true, rollbackSupport: seed.rollback ?? "manual" },
    ],
    permissionScopes: seed.scopes,
    sandbox: {
      available: true,
      defaultMode: defaultRisk === "low" ? "read_only" : "approval_required",
      notes: "Operators can inspect and prepare work first; risky external or irreversible actions require approval.",
    },
    artifactSupport: seed.artifacts ?? ["document", "spreadsheet", "json", "external_link"],
    rollbackSupport: seed.rollback ?? "manual",
  };
}

export const UNIVERSAL_CONNECTOR_CATALOG: UniversalConnectorDefinition[] = [
  {
    id: "blender_local_bridge",
    label: "Blender",
    provider: "blender",
    kind: "local_bridge",
    category: "engineering",
    description: "Let Operators create, revise, render, and export Blender scenes through a local bridge or MCP server.",
    whatItEnables: [
      "Create 3D scenes from prompts and references.",
      "Revise materials, lighting, cameras, and composition from chat feedback.",
      "Render preview images and export .blend, .glb, .obj, .stl, or video artifacts.",
      "Keep every revision attached to Operator Chat.",
    ],
    examplePrompts: [
      "Create a premium 3D bottle render using this reference image.",
      "Make the model matte black, add warm rust lighting, and show three camera angles.",
      "Export a GLB and attach the Blender file after approval.",
    ],
    setupSteps: [
      "Install the Dobly Blender bridge add-on or run a Blender MCP server.",
      "Start Blender with the bridge enabled.",
      "Paste the local bridge URL or MCP server URL into Dobly.",
      "Run Test Connection and Discover Tools.",
      "Choose which Operators may use Blender and what actions require approval.",
    ],
    requiredUserInputs: [
      { key: "serverUrl", label: "Local bridge or MCP URL", type: "url", required: true, help: "Usually http://localhost:port or a hosted MCP endpoint." },
      { key: "authToken", label: "Bridge token", type: "token", required: false, help: "Optional token if your bridge requires authentication." },
    ],
    capabilities: caps("3d cad design render media artifact operate software engineering blender"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_scene", description: "Inspect the current scene.", riskLevel: "low", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "create_or_modify_scene", description: "Create or change objects, materials, cameras, or lighting.", riskLevel: "medium", approvalRequired: true, rollbackSupport: "versioned_artifact" },
      { action: "export_file", description: "Export a model, render, or animation.", riskLevel: "medium", approvalRequired: true, rollbackSupport: "versioned_artifact" },
      { action: "run_python", description: "Run arbitrary Blender Python.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read scene", "Create drafts", "Render previews", "Export artifacts", "Run approved scripts"],
    sandbox: { available: true, defaultMode: "draft_only", notes: "Operators should create drafts and previews first, then ask before export or destructive changes." },
    localBridge: { required: true, name: "Dobly Blender Bridge", installHint: "Install the Blender add-on or run the Blender MCP bridge locally.", healthPath: "/health" },
    artifactSupport: ["image", "video", "cad", "json", "external_link"],
    rollbackSupport: "versioned_artifact",
  },
  {
    id: "figma_mcp",
    label: "Figma",
    provider: "figma",
    kind: "mcp",
    category: "design",
    description: "Let Operators inspect, create, and revise Figma designs through an MCP server.",
    whatItEnables: ["Create UI drafts.", "Revise design files from chat feedback.", "Attach previews and design links.", "Generate implementation notes."],
    examplePrompts: ["Turn this landing page into a premium Figma mockup.", "Update the hero layout and show the new frame.", "Generate a design handoff spec."],
    setupSteps: ["Connect your Figma account.", "Dobly routes through its hosted Figma connector.", "Discover available design tools.", "Assign permission scopes to Operators."],
    requiredUserInputs: [
      { key: "oauth", label: "Figma account", type: "oauth", required: true, help: "Connect Figma through Dobly-hosted setup." },
    ],
    capabilities: caps("figma design ui document artifact operate software"),
    defaultRisk: "medium",
    approvalPolicies: [
      { action: "read_file", description: "Inspect file structure and frames.", riskLevel: "low", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "create_draft", description: "Create new draft frames.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "versioned_artifact" },
      { action: "modify_existing", description: "Modify existing source frames.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read files", "Create draft frames", "Modify selected files", "Export previews"],
    sandbox: { available: true, defaultMode: "draft_only", notes: "Prefer draft pages/branches before editing source design files." },
    artifactSupport: ["image", "document", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "github_oauth_mcp",
    label: "GitHub",
    provider: "github",
    kind: "mcp",
    category: "code",
    description: "Let Operators inspect repos, triage issues, draft changes, and prepare pull requests.",
    whatItEnables: ["Read repositories and issues.", "Draft code changes.", "Open PRs after approval.", "Attach diffs and release notes."],
    examplePrompts: ["Investigate this bug and draft a fix.", "Write release notes from merged PRs.", "Open a PR only after I approve the diff."],
    setupSteps: ["Connect your GitHub account.", "Choose repositories.", "Set write/PR approval rules.", "Run test repository access."],
    requiredUserInputs: [
      { key: "oauth", label: "GitHub account", type: "oauth", required: true, help: "Connect GitHub access." },
    ],
    capabilities: caps("github code engineering issue repository release operate software"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_repo", description: "Read code, issues, and metadata.", riskLevel: "low", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "draft_patch", description: "Prepare code changes as artifacts.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "versioned_artifact" },
      { action: "push_or_pr", description: "Push changes or open pull requests.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read repositories", "Read issues", "Draft patches", "Open PRs", "Write after approval"],
    sandbox: { available: true, defaultMode: "draft_only", notes: "Use branch/diff artifacts until the user approves external repository changes." },
    artifactSupport: ["document", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "canva_media",
    label: "Canva",
    provider: "canva",
    kind: "mcp",
    category: "media",
    description: "Let Operators create and revise social graphics, thumbnails, templates, and campaign assets.",
    whatItEnables: ["Create design drafts.", "Resize creative for platforms.", "Attach previews.", "Prepare publish-ready packages."],
    examplePrompts: ["Create Instagram and LinkedIn versions of this launch graphic.", "Make a YouTube thumbnail from this title.", "Revise the design using Dobly colors."],
    setupSteps: ["Connect your Canva account.", "Choose brand kit or workspace.", "Discover design/export tools.", "Set publishing approvals."],
    requiredUserInputs: [{ key: "oauth", label: "Canva account", type: "oauth", required: true, help: "Connect Canva through Dobly-hosted setup." }],
    capabilities: caps("media design social image video artifact"),
    defaultRisk: "medium",
    approvalPolicies: [
      { action: "create_design", description: "Create a new design draft.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "versioned_artifact" },
      { action: "publish_or_share", description: "Publish or share externally.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Create designs", "Use brand kit", "Export assets", "Share after approval"],
    sandbox: { available: true, defaultMode: "draft_only", notes: "Creative should be reviewed in chat before publishing or sharing." },
    artifactSupport: ["image", "video", "document", "external_link"],
    rollbackSupport: "versioned_artifact",
  },
  {
    id: "gmail_oauth",
    label: "Gmail",
    provider: "gmail",
    kind: "oauth",
    category: "communication",
    description: "Let Operators draft, summarize, label, and send email with approval controls.",
    whatItEnables: ["Draft replies.", "Summarize inbox threads.", "Send approved emails.", "Create follow-up loops."],
    examplePrompts: ["Draft replies for these leads and ask before sending.", "Summarize customer complaints from this week.", "Follow up on unpaid invoices."],
    setupSteps: ["Connect Google account.", "Choose scopes.", "Set send approval rules.", "Run test inbox read."],
    requiredUserInputs: [{ key: "oauth", label: "Google account", type: "oauth", required: true, help: "Connect Gmail access." }],
    capabilities: caps("email communication sales support finance"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_email", description: "Read and summarize email.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "draft_email", description: "Create drafts.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "manual" },
      { action: "send_email", description: "Send email externally.", riskLevel: "high", approvalRequired: true, rollbackSupport: "not_available" },
    ],
    permissionScopes: ["Read inbox", "Create drafts", "Send after approval", "Manage labels"],
    sandbox: { available: true, defaultMode: "approval_required", notes: "External sends should stay approval-gated by default." },
    artifactSupport: ["document", "json", "external_link"],
    rollbackSupport: "not_available",
  },
  {
    id: "whatsapp_business",
    label: "WhatsApp Business",
    provider: "whatsapp",
    kind: "native",
    category: "communication",
    description: "Let Reception, Sales, and Support Operators respond to WhatsApp conversations.",
    whatItEnables: ["Handle inbound WhatsApp.", "Qualify leads.", "Escalate important messages.", "Send approved replies and templates."],
    examplePrompts: ["Answer inbound WhatsApp inquiries and book appointments.", "Escalate pricing questions to me.", "Summarize today's WhatsApp conversations."],
    setupSteps: ["Connect Meta WhatsApp Business.", "Verify phone/webhook.", "Choose templates.", "Set send and escalation rules."],
    requiredUserInputs: [{ key: "oauth", label: "Meta/WhatsApp account", type: "oauth", required: true, help: "Connect WhatsApp Business access." }],
    capabilities: caps("whatsapp communication sales support reception"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_messages", description: "Read inbound messages.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "send_message", description: "Send outbound message.", riskLevel: "high", approvalRequired: true, rollbackSupport: "not_available" },
    ],
    permissionScopes: ["Read messages", "Draft replies", "Send approved replies", "Escalate conversations"],
    sandbox: { available: true, defaultMode: "approval_required", notes: "Draft mode first for new Operators, then trusted paths can be relaxed." },
    artifactSupport: ["document", "audio", "image", "json"],
    rollbackSupport: "not_available",
  },
  {
    id: "google_workspace_oauth",
    label: "Google Workspace",
    provider: "google_workspace",
    kind: "oauth",
    category: "documents",
    description: "Let Operators work across Google Drive, Docs, Sheets, Calendar, and Workspace files from one Google connection.",
    whatItEnables: ["Read and organize Drive files.", "Create Docs and Sheets.", "Update approved workspace files.", "Attach generated artifacts back to chats and runs."],
    examplePrompts: ["Turn this research into a Google Doc.", "Update my weekly KPI sheet.", "Find the contract folder and summarize what changed."],
    setupSteps: ["Connect Google Workspace.", "Choose Drive, Docs, Sheets, and Calendar scopes.", "Pick folders or workspaces Operators can access.", "Set edit/share approvals."],
    requiredUserInputs: [{ key: "oauth", label: "Google Workspace account", type: "oauth", required: true, help: "Connect Google Workspace access." }],
    capabilities: caps("document spreadsheet calendar google drive docs sheets operate software"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_files", description: "Read selected Drive files and folders.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "create_file", description: "Create Docs, Sheets, and folders.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "manual" },
      { action: "edit_or_share", description: "Edit existing files or share externally.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read selected Drive files", "Create Docs", "Create Sheets", "Edit after approval", "Share after approval"],
    sandbox: { available: true, defaultMode: "draft_only", notes: "Operators create drafts first and ask before changing or sharing important workspace files." },
    artifactSupport: ["document", "spreadsheet", "image", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "google_calendar_oauth",
    label: "Google Calendar",
    provider: "google_calendar",
    kind: "oauth",
    category: "communication",
    description: "Let Operators read availability, schedule meetings, move events, and manage follow-up loops with approval rules.",
    whatItEnables: ["Check availability.", "Draft meeting bookings.", "Reschedule approved events.", "Connect meetings to sales, support, travel, and admin loops."],
    examplePrompts: ["Book qualified leads into open calendar slots.", "Move tomorrow's calls to next week and ask before sending updates.", "Prepare my day every morning."],
    setupSteps: ["Connect Google Calendar.", "Choose calendars Operators may see.", "Set booking and reschedule approval rules.", "Run a test availability check."],
    requiredUserInputs: [{ key: "oauth", label: "Google Calendar account", type: "oauth", required: true, help: "Connect calendar access." }],
    capabilities: caps("calendar meeting appointment schedule send message"),
    defaultRisk: "medium",
    approvalPolicies: [
      { action: "read_availability", description: "Read calendar availability.", riskLevel: "low", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "create_event", description: "Create meeting holds or draft events.", riskLevel: "medium", approvalRequired: true, rollbackSupport: "manual" },
      { action: "change_event", description: "Reschedule, cancel, or invite guests.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read availability", "Create draft events", "Invite after approval", "Reschedule after approval"],
    sandbox: { available: true, defaultMode: "approval_required", notes: "Calendar changes affect people, so booking and rescheduling stay approval-gated by default." },
    artifactSupport: ["document", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "microsoft_365_oauth",
    label: "Microsoft 365",
    provider: "microsoft_365",
    kind: "oauth",
    category: "documents",
    description: "Let Operators use Outlook, OneDrive, Word, Excel, Teams, and Microsoft workspaces with approval controls.",
    whatItEnables: ["Draft Outlook replies.", "Create Word and Excel files.", "Organize OneDrive files.", "Summarize Teams context."],
    examplePrompts: ["Draft replies in Outlook and ask before sending.", "Create an Excel cashflow report.", "Summarize this OneDrive folder."],
    setupSteps: ["Connect Microsoft 365.", "Choose Outlook, OneDrive, Calendar, and Teams scopes.", "Pick accessible folders or teams.", "Set send/edit/share approvals."],
    requiredUserInputs: [{ key: "oauth", label: "Microsoft account", type: "oauth", required: true, help: "Connect Microsoft 365 access." }],
    capabilities: caps("email calendar document spreadsheet teams message operate software"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_workspace", description: "Read selected email, files, and team context.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "create_draft", description: "Create drafts, files, or reports.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "manual" },
      { action: "send_edit_share", description: "Send, edit existing files, or share externally.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read selected workspace", "Create drafts", "Create files", "Send after approval", "Edit/share after approval"],
    sandbox: { available: true, defaultMode: "approval_required", notes: "Operators should draft first, then ask before external sends or existing-file edits." },
    artifactSupport: ["document", "spreadsheet", "audio", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "slack_oauth",
    label: "Slack",
    provider: "slack",
    kind: "oauth",
    category: "communication",
    description: "Let Operators monitor channels, draft replies, summarize discussions, and escalate work from Slack.",
    whatItEnables: ["Summarize channels.", "Draft replies.", "Create follow-up tasks.", "Escalate important messages to Operator Chat."],
    examplePrompts: ["Summarize customer issues from support channels.", "Watch mentions of launch blockers.", "Draft a team update for approval."],
    setupSteps: ["Connect Slack workspace.", "Choose channels and scopes.", "Set send/escalation approval rules.", "Run a test channel summary."],
    requiredUserInputs: [{ key: "oauth", label: "Slack workspace", type: "oauth", required: true, help: "Connect Slack access." }],
    capabilities: caps("message communication support project task"),
    defaultRisk: "medium",
    approvalPolicies: [
      { action: "read_channels", description: "Read selected channels.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "draft_reply", description: "Draft a reply or update.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "manual" },
      { action: "post_message", description: "Post into Slack.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read selected channels", "Draft replies", "Post after approval", "Create follow-ups"],
    sandbox: { available: true, defaultMode: "approval_required", notes: "Operators can monitor and draft, but posting is approval-gated by default." },
    artifactSupport: ["document", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "hubspot_oauth",
    label: "HubSpot",
    provider: "hubspot",
    kind: "oauth",
    category: "crm",
    description: "Let Sales, Support, and Growth Operators manage CRM context, deals, contacts, tickets, and follow-ups.",
    whatItEnables: ["Read contacts and deals.", "Update CRM records.", "Create tasks and tickets.", "Connect sales loops to real pipeline data."],
    examplePrompts: ["Qualify new leads and update HubSpot.", "Find deals stuck for more than 14 days.", "Create follow-up tasks for warm leads."],
    setupSteps: ["Connect HubSpot.", "Choose CRM object scopes.", "Map owners and pipelines.", "Set approval rules for updates and outbound communication."],
    requiredUserInputs: [{ key: "oauth", label: "HubSpot account", type: "oauth", required: true, help: "Connect HubSpot access." }],
    capabilities: caps("crm lead pipeline deal customer record sales support"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_crm", description: "Read contacts, companies, deals, and tickets.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "create_task", description: "Create CRM tasks or notes.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "manual" },
      { action: "update_record", description: "Change CRM records, deal stages, or owners.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read CRM", "Create tasks", "Create notes", "Update after approval", "Trigger follow-ups"],
    sandbox: { available: true, defaultMode: "approval_required", notes: "CRM writes can affect revenue workflows, so important updates ask first." },
    artifactSupport: ["document", "spreadsheet", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "instagram_business_oauth",
    label: "Instagram",
    provider: "instagram",
    kind: "oauth",
    category: "social",
    description: "Let Marketing Operators prepare, schedule, publish, and analyze Instagram posts, reels, stories, and comments.",
    whatItEnables: ["Draft captions and creative packages.", "Schedule content.", "Publish after approval.", "Pull performance signals into growth loops."],
    examplePrompts: ["Turn this launch into three reels and captions.", "Schedule next week's posts but ask before publishing.", "Summarize what content performed best."],
    setupSteps: ["Connect Instagram Business through Meta.", "Choose page/account access.", "Set publish and comment approval rules.", "Run a test media permission check."],
    requiredUserInputs: [{ key: "oauth", label: "Instagram Business account", type: "oauth", required: true, help: "Connect via Meta Business access." }],
    capabilities: caps("instagram social publish post schedule media video image"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_insights", description: "Read analytics and comments.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "create_content_package", description: "Prepare captions and media drafts.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "versioned_artifact" },
      { action: "publish_content", description: "Publish posts, reels, stories, or replies.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read insights", "Draft content", "Schedule after approval", "Publish after approval", "Reply after approval"],
    sandbox: { available: true, defaultMode: "draft_only", notes: "Content is generated as a reviewable package before anything goes live." },
    artifactSupport: ["image", "video", "document", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "facebook_pages_oauth",
    label: "Facebook Pages",
    provider: "facebook",
    kind: "oauth",
    category: "social",
    description: "Let Operators manage Facebook Pages, posts, comments, messages, and performance signals.",
    whatItEnables: ["Draft page posts.", "Monitor comments and messages.", "Publish after approval.", "Summarize page analytics."],
    examplePrompts: ["Draft a Facebook campaign from this offer.", "Monitor comments and escalate angry customers.", "Publish this approved post tomorrow morning."],
    setupSteps: ["Connect Meta Business.", "Choose Facebook Pages.", "Set messaging, comment, and publish approvals.", "Run test page access."],
    requiredUserInputs: [{ key: "oauth", label: "Meta/Facebook account", type: "oauth", required: true, help: "Connect Facebook Page access." }],
    capabilities: caps("facebook social publish post message support media"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_page", description: "Read page insights, posts, comments, and messages.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "draft_post", description: "Create draft post packages.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "versioned_artifact" },
      { action: "publish_or_reply", description: "Publish posts or reply publicly.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read page", "Draft posts", "Read messages", "Publish after approval", "Reply after approval"],
    sandbox: { available: true, defaultMode: "approval_required", notes: "Public posts and customer replies require approval until trust rules are changed." },
    artifactSupport: ["image", "video", "document", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "linkedin_oauth",
    label: "LinkedIn",
    provider: "linkedin",
    kind: "oauth",
    category: "social",
    description: "Let Growth and Founder Operators draft, schedule, publish, and analyze LinkedIn personal or company content.",
    whatItEnables: ["Draft thought-leadership posts.", "Prepare company updates.", "Schedule approved posts.", "Track engagement and content learnings."],
    examplePrompts: ["Turn this idea into a founder LinkedIn post.", "Prepare a launch post for the company page.", "Tell me what topics are getting traction."],
    setupSteps: ["Connect LinkedIn.", "Choose personal or company page permissions.", "Set publish approval rules.", "Run test account access."],
    requiredUserInputs: [{ key: "oauth", label: "LinkedIn account", type: "oauth", required: true, help: "Connect LinkedIn access." }],
    capabilities: caps("linkedin social publish post schedule content media"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_profile_or_page", description: "Read profile/page metadata and post analytics.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "draft_post", description: "Prepare post drafts and variants.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "versioned_artifact" },
      { action: "publish_post", description: "Publish to profile or company page.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read profile/page", "Draft posts", "Schedule after approval", "Publish after approval", "Read analytics"],
    sandbox: { available: true, defaultMode: "draft_only", notes: "Operators draft and attach versions in chat before publishing." },
    artifactSupport: ["document", "image", "video", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "x_oauth",
    label: "X",
    provider: "x",
    kind: "oauth",
    category: "social",
    description: "Let Operators draft posts, monitor mentions, schedule threads, and summarize audience signals on X.",
    whatItEnables: ["Draft posts and threads.", "Monitor mentions.", "Publish after approval.", "Track content and competitor signals."],
    examplePrompts: ["Turn this announcement into a sharp X thread.", "Watch mentions of our brand and alert me.", "Schedule three approved posts this week."],
    setupSteps: ["Connect X account.", "Choose read/write scopes.", "Set publish/reply approval rules.", "Run test account access."],
    requiredUserInputs: [{ key: "oauth", label: "X account", type: "oauth", required: true, help: "Connect X access." }],
    capabilities: caps("x twitter social publish post schedule message research"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_mentions", description: "Read posts, mentions, and analytics.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "draft_thread", description: "Prepare posts or threads.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "versioned_artifact" },
      { action: "publish_or_reply", description: "Publish posts or replies.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read mentions", "Draft posts", "Schedule after approval", "Publish after approval", "Reply after approval"],
    sandbox: { available: true, defaultMode: "approval_required", notes: "Public posts and replies stay approval-gated by default." },
    artifactSupport: ["document", "image", "video", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "youtube_oauth",
    label: "YouTube",
    provider: "youtube",
    kind: "oauth",
    category: "social",
    description: "Let Operators prepare uploads, Shorts, descriptions, thumbnails, schedules, and analytics summaries.",
    whatItEnables: ["Prepare video packages.", "Upload drafts.", "Schedule after approval.", "Pull analytics into growth memory."],
    examplePrompts: ["Prepare this video for YouTube with title, description, and thumbnail.", "Schedule this Short after I approve it.", "Summarize last month's channel performance."],
    setupSteps: ["Connect YouTube channel.", "Choose upload and analytics scopes.", "Set upload/publish approval rules.", "Run test channel access."],
    requiredUserInputs: [{ key: "oauth", label: "YouTube channel", type: "oauth", required: true, help: "Connect YouTube access." }],
    capabilities: caps("youtube video media publish upload thumbnail analytics"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_analytics", description: "Read channel and video analytics.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "prepare_upload", description: "Prepare upload metadata and assets.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "versioned_artifact" },
      { action: "upload_or_publish", description: "Upload, schedule, or publish video.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read analytics", "Prepare uploads", "Upload after approval", "Publish after approval", "Manage thumbnails"],
    sandbox: { available: true, defaultMode: "draft_only", notes: "Video packages are reviewed before upload or publish." },
    artifactSupport: ["video", "image", "document", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "tiktok_oauth",
    label: "TikTok",
    provider: "tiktok",
    kind: "oauth",
    category: "social",
    description: "Let Operators prepare TikTok videos, captions, schedules, comments, and performance insights.",
    whatItEnables: ["Prepare short-form video packages.", "Draft captions and hashtags.", "Publish after approval.", "Track content performance."],
    examplePrompts: ["Turn this product update into three TikToks.", "Draft hooks and captions for this video.", "Tell me which TikTok format is working."],
    setupSteps: ["Connect TikTok account.", "Choose content and analytics scopes.", "Set publish/reply approval rules.", "Run test profile access."],
    requiredUserInputs: [{ key: "oauth", label: "TikTok account", type: "oauth", required: true, help: "Connect TikTok access." }],
    capabilities: caps("tiktok video media social publish post schedule analytics"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_analytics", description: "Read content analytics.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "prepare_video", description: "Prepare video/caption packages.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "versioned_artifact" },
      { action: "publish_or_reply", description: "Publish videos or reply publicly.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read analytics", "Draft videos", "Schedule after approval", "Publish after approval", "Reply after approval"],
    sandbox: { available: true, defaultMode: "draft_only", notes: "Operators create reviewable content packages before publishing." },
    artifactSupport: ["video", "image", "document", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "shopify_oauth",
    label: "Shopify",
    provider: "shopify",
    kind: "oauth",
    category: "commerce",
    description: "Let Commerce and Fulfillment Operators inspect orders, products, inventory, customers, and refunds.",
    whatItEnables: ["Track orders.", "Prepare refunds.", "Monitor inventory.", "Update products after approval."],
    examplePrompts: ["Summarize delayed orders and prepare customer updates.", "Find low-stock products.", "Prepare a refund but ask before issuing it."],
    setupSteps: ["Connect Shopify store.", "Choose store scopes.", "Set money/product change approvals.", "Run test order read."],
    requiredUserInputs: [{ key: "oauth", label: "Shopify store", type: "oauth", required: true, help: "Connect Shopify access." }],
    capabilities: caps("commerce inventory order fulfillment customer finance"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_orders", description: "Read orders and customers.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "update_product", description: "Update products or inventory.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
      { action: "refund_or_charge", description: "Move money.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read orders", "Read products", "Draft updates", "Write after approval", "Prepare refunds"],
    sandbox: { available: true, defaultMode: "approval_required", notes: "Money movement and product changes require approval." },
    artifactSupport: ["spreadsheet", "document", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "stripe_oauth",
    label: "Stripe",
    provider: "stripe",
    kind: "oauth",
    category: "finance",
    description: "Let Finance and Commerce Operators inspect payments, prepare invoices, monitor failed payments, and request approval before money movement.",
    whatItEnables: ["Track payments and customers.", "Prepare invoices and checkout links.", "Monitor failed payments.", "Escalate refunds and charges for approval."],
    examplePrompts: ["Find failed payments and draft follow-ups.", "Prepare an invoice for this client.", "Summarize revenue and refunds this week."],
    setupSteps: ["Connect Stripe.", "Choose payment, invoice, and customer scopes.", "Set money movement approval rules.", "Run test payment read."],
    requiredUserInputs: [{ key: "oauth", label: "Stripe account", type: "oauth", required: true, help: "Connect Stripe access." }],
    capabilities: caps("stripe payment charge invoice customer finance"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_payments", description: "Read payments, customers, and invoices.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "create_invoice_draft", description: "Prepare invoice or payment link drafts.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
      { action: "refund_or_charge", description: "Refund, charge, or collect money.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read payments", "Read customers", "Prepare invoices", "Create payment links after approval", "Refund after approval"],
    sandbox: { available: true, defaultMode: "approval_required", notes: "Any money movement or customer billing action requires approval." },
    artifactSupport: ["document", "spreadsheet", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "quickbooks_oauth",
    label: "QuickBooks",
    provider: "quickbooks",
    kind: "oauth",
    category: "finance",
    description: "Let Finance Operators create invoice drafts, reconcile transactions, inspect reports, and prepare accounting updates.",
    whatItEnables: ["Read financial reports.", "Draft invoices.", "Reconcile transactions.", "Prepare cashflow summaries."],
    examplePrompts: ["Reconcile yesterday's payments.", "Draft overdue invoice reminders.", "Prepare a cashflow report for approval."],
    setupSteps: ["Connect QuickBooks.", "Choose company and accounting scopes.", "Set invoice/payment approval rules.", "Run test report read."],
    requiredUserInputs: [{ key: "oauth", label: "QuickBooks company", type: "oauth", required: true, help: "Connect QuickBooks access." }],
    capabilities: caps("quickbooks invoice accounting reconcile finance expense payment"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_books", description: "Read reports, invoices, and transactions.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "draft_accounting_entry", description: "Prepare invoice, expense, or reconciliation drafts.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
      { action: "post_accounting_change", description: "Post accounting changes.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read reports", "Read invoices", "Draft invoices", "Draft reconciliations", "Post after approval"],
    sandbox: { available: true, defaultMode: "approval_required", notes: "Accounting writes stay approval-gated to protect the books." },
    artifactSupport: ["document", "spreadsheet", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "xero_oauth",
    label: "Xero",
    provider: "xero",
    kind: "oauth",
    category: "finance",
    description: "Let Finance Operators inspect accounts, draft invoices, reconcile payments, and prepare finance reports.",
    whatItEnables: ["Read accounting records.", "Draft invoices and bills.", "Reconcile payments.", "Generate finance reports."],
    examplePrompts: ["Reconcile bank transactions and show exceptions.", "Draft invoices for approved work.", "Summarize overdue receivables."],
    setupSteps: ["Connect Xero.", "Choose organization and scopes.", "Set accounting write approvals.", "Run test ledger read."],
    requiredUserInputs: [{ key: "oauth", label: "Xero organization", type: "oauth", required: true, help: "Connect Xero access." }],
    capabilities: caps("xero invoice accounting reconcile finance expense payment"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_accounting", description: "Read accounting data and reports.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "draft_invoice_or_bill", description: "Draft invoices, bills, and reconciliation notes.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
      { action: "post_accounting_change", description: "Post financial changes.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read accounting", "Draft invoices", "Draft bills", "Draft reconciliations", "Post after approval"],
    sandbox: { available: true, defaultMode: "approval_required", notes: "Finance writes and money-related changes require approval." },
    artifactSupport: ["document", "spreadsheet", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "salesforce_oauth",
    label: "Salesforce",
    provider: "salesforce",
    kind: "oauth",
    category: "crm",
    description: "Let Sales and Customer Operators inspect accounts, opportunities, cases, tasks, and pipeline movement.",
    whatItEnables: ["Read accounts and opportunities.", "Create follow-up tasks.", "Update pipeline after approval.", "Summarize sales and support activity."],
    examplePrompts: ["Find stalled opportunities and draft next steps.", "Summarize this account before my call.", "Update stages after I approve."],
    setupSteps: ["Connect Salesforce.", "Choose object scopes.", "Map pipelines and owners.", "Set record update approvals."],
    requiredUserInputs: [{ key: "oauth", label: "Salesforce account", type: "oauth", required: true, help: "Connect Salesforce access." }],
    capabilities: caps("salesforce crm lead pipeline opportunity customer record sales support"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_crm", description: "Read Salesforce records.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "create_task_or_note", description: "Create tasks and notes.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "manual" },
      { action: "update_record", description: "Update opportunities, cases, owners, or account data.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read objects", "Create tasks", "Create notes", "Update after approval", "Sync outcomes"],
    sandbox: { available: true, defaultMode: "approval_required", notes: "Pipeline and account changes require approval until explicitly trusted." },
    artifactSupport: ["document", "spreadsheet", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "pipedrive_oauth",
    label: "Pipedrive",
    provider: "pipedrive",
    kind: "oauth",
    category: "crm",
    description: "Let Sales Operators manage deals, contacts, activities, pipeline follow-ups, and sales reporting.",
    whatItEnables: ["Read deals and contacts.", "Create activities.", "Prepare pipeline updates.", "Connect sales loops to CRM reality."],
    examplePrompts: ["Create follow-ups for warm deals.", "Find every deal with no next step.", "Draft a pipeline report."],
    setupSteps: ["Connect Pipedrive.", "Choose CRM scopes.", "Map pipelines.", "Set update and outbound approval rules."],
    requiredUserInputs: [{ key: "oauth", label: "Pipedrive account", type: "oauth", required: true, help: "Connect Pipedrive access." }],
    capabilities: caps("pipedrive crm deal pipeline lead sales task"),
    defaultRisk: "high",
    approvalPolicies: [
      { action: "read_pipeline", description: "Read contacts, deals, and activities.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "create_activity", description: "Create tasks or activities.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "manual" },
      { action: "update_deal", description: "Move deals or update records.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read pipeline", "Create activities", "Create notes", "Update deals after approval"],
    sandbox: { available: true, defaultMode: "approval_required", notes: "Operators can draft CRM changes and ask before committing them." },
    artifactSupport: ["document", "spreadsheet", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "airtable_oauth",
    label: "Airtable",
    provider: "airtable",
    kind: "oauth",
    category: "data",
    description: "Let Operators use Airtable bases as lightweight databases for operations, content, CRM, projects, inventory, and research.",
    whatItEnables: ["Read bases and records.", "Create draft records.", "Update operational data after approval.", "Generate reports from Airtable data."],
    examplePrompts: ["Turn this spreadsheet into an Airtable update plan.", "Find content items due this week.", "Update inventory rows after approval."],
    setupSteps: ["Connect Airtable.", "Choose bases and tables.", "Map important fields.", "Set create/update/delete approval rules."],
    requiredUserInputs: [{ key: "oauth", label: "Airtable account", type: "oauth", required: true, help: "Connect Airtable access." }],
    capabilities: caps("airtable database spreadsheet project crm inventory data"),
    defaultRisk: "medium",
    approvalPolicies: [
      { action: "read_records", description: "Read selected bases and records.", riskLevel: "low", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "create_record", description: "Create new records.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "manual" },
      { action: "update_or_delete", description: "Update or delete existing records.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read bases", "Create records", "Update after approval", "Delete after approval", "Generate reports"],
    sandbox: { available: true, defaultMode: "draft_only", notes: "Existing data changes are approval-gated; new records can be drafted first." },
    artifactSupport: ["spreadsheet", "document", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "asana_oauth",
    label: "Asana",
    provider: "asana",
    kind: "oauth",
    category: "personal",
    description: "Let Operators manage projects, tasks, owners, status updates, and follow-up loops in Asana.",
    whatItEnables: ["Read project state.", "Create tasks.", "Draft status updates.", "Keep delegated work moving."],
    examplePrompts: ["Create project tasks from this meeting.", "Find overdue tasks and draft follow-ups.", "Prepare a weekly project update."],
    setupSteps: ["Connect Asana.", "Choose workspaces and projects.", "Set task creation/update approval rules.", "Run test project access."],
    requiredUserInputs: [{ key: "oauth", label: "Asana account", type: "oauth", required: true, help: "Connect Asana access." }],
    capabilities: caps("asana task project assign status"),
    defaultRisk: "medium",
    approvalPolicies: [
      { action: "read_projects", description: "Read tasks and projects.", riskLevel: "low", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "create_task", description: "Create tasks and subtasks.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "manual" },
      { action: "update_or_assign", description: "Change owners, due dates, or status.", riskLevel: "medium", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read projects", "Create tasks", "Comment", "Update after approval", "Assign after approval"],
    sandbox: { available: true, defaultMode: "draft_only", notes: "Operators can draft project updates before changing owners or deadlines." },
    artifactSupport: ["document", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "trello_oauth",
    label: "Trello",
    provider: "trello",
    kind: "oauth",
    category: "personal",
    description: "Let Operators manage boards, cards, checklists, labels, and lightweight project movement in Trello.",
    whatItEnables: ["Read boards.", "Create cards.", "Move work after approval.", "Summarize project status."],
    examplePrompts: ["Turn this plan into Trello cards.", "Find blocked cards.", "Prepare a project board summary."],
    setupSteps: ["Connect Trello.", "Choose boards.", "Set card movement approval rules.", "Run test board access."],
    requiredUserInputs: [{ key: "oauth", label: "Trello account", type: "oauth", required: true, help: "Connect Trello access." }],
    capabilities: caps("trello task project board status"),
    defaultRisk: "medium",
    approvalPolicies: [
      { action: "read_boards", description: "Read boards and cards.", riskLevel: "low", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "create_card", description: "Create cards and checklists.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "manual" },
      { action: "move_or_archive", description: "Move, archive, or assign cards.", riskLevel: "medium", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read boards", "Create cards", "Comment", "Move after approval", "Archive after approval"],
    sandbox: { available: true, defaultMode: "draft_only", notes: "Operators draft card changes before moving or archiving important work." },
    artifactSupport: ["document", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "linear_oauth",
    label: "Linear",
    provider: "linear",
    kind: "oauth",
    category: "engineering",
    description: "Let Engineering Operators inspect issues, triage bugs, create specs, and coordinate release work in Linear.",
    whatItEnables: ["Read issues.", "Create bugs and tasks.", "Draft specs and release notes.", "Update engineering work after approval."],
    examplePrompts: ["Turn this bug report into a Linear issue.", "Find blockers for this release.", "Draft release notes from completed issues."],
    setupSteps: ["Connect Linear.", "Choose teams and projects.", "Set issue update approval rules.", "Run test issue read."],
    requiredUserInputs: [{ key: "oauth", label: "Linear workspace", type: "oauth", required: true, help: "Connect Linear access." }],
    capabilities: caps("linear issue engineering project task release bug"),
    defaultRisk: "medium",
    approvalPolicies: [
      { action: "read_issues", description: "Read teams, projects, and issues.", riskLevel: "low", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "create_issue", description: "Create issues and comments.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "manual" },
      { action: "update_issue", description: "Change priority, status, assignee, or project.", riskLevel: "medium", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read issues", "Create issues", "Comment", "Update after approval", "Create release notes"],
    sandbox: { available: true, defaultMode: "draft_only", notes: "Operators can create clear drafts and ask before changing project state." },
    artifactSupport: ["document", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "calendly_oauth",
    label: "Calendly",
    provider: "calendly",
    kind: "oauth",
    category: "communication",
    description: "Let Reception and Sales Operators create booking flows, inspect scheduled events, and send approved scheduling links.",
    whatItEnables: ["Read event types.", "Share booking links.", "Track scheduled meetings.", "Connect lead qualification to bookings."],
    examplePrompts: ["Send qualified leads the right booking link.", "Summarize this week's scheduled demos.", "Route support calls into the correct event type."],
    setupSteps: ["Connect Calendly.", "Choose event types.", "Set send/link approval rules.", "Run test event read."],
    requiredUserInputs: [{ key: "oauth", label: "Calendly account", type: "oauth", required: true, help: "Connect Calendly access." }],
    capabilities: caps("calendar meeting schedule appointment sales support"),
    defaultRisk: "medium",
    approvalPolicies: [
      { action: "read_events", description: "Read event types and scheduled events.", riskLevel: "low", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "send_booking_link", description: "Send booking links externally.", riskLevel: "high", approvalRequired: true, rollbackSupport: "not_available" },
      { action: "change_event_type", description: "Change event type settings.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read event types", "Read bookings", "Send links after approval", "Update settings after approval"],
    sandbox: { available: true, defaultMode: "approval_required", notes: "Operators can recommend booking links but ask before sending externally." },
    artifactSupport: ["document", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "dropbox_oauth",
    label: "Dropbox",
    provider: "dropbox",
    kind: "oauth",
    category: "documents",
    description: "Let Operators find, organize, summarize, and produce files inside Dropbox with folder-level controls.",
    whatItEnables: ["Find files.", "Create folder summaries.", "Upload generated artifacts.", "Organize folders after approval."],
    examplePrompts: ["Find the latest contract and summarize it.", "Upload the approved proposal to the client folder.", "Organize these files by project."],
    setupSteps: ["Connect Dropbox.", "Choose folders Operators can access.", "Set upload/move/delete approval rules.", "Run test folder read."],
    requiredUserInputs: [{ key: "oauth", label: "Dropbox account", type: "oauth", required: true, help: "Connect Dropbox access." }],
    capabilities: caps("dropbox file document folder operate software"),
    defaultRisk: "medium",
    approvalPolicies: [
      { action: "read_files", description: "Read selected folders and files.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "upload_file", description: "Upload generated artifacts.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "manual" },
      { action: "move_or_delete", description: "Move, rename, or delete files.", riskLevel: "high", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read selected folders", "Upload artifacts", "Create folders", "Move after approval", "Delete after approval"],
    sandbox: { available: true, defaultMode: "draft_only", notes: "File deletes and major reorganizations require approval." },
    artifactSupport: ["document", "spreadsheet", "image", "video", "audio", "json", "external_link"],
    rollbackSupport: "manual",
  },
  {
    id: "notion_mcp",
    label: "Notion",
    provider: "notion",
    kind: "mcp",
    category: "documents",
    description: "Let Operators create and update docs, knowledge bases, task databases, and operating records.",
    whatItEnables: ["Create pages.", "Summarize docs.", "Update task databases.", "Store SOPs and reports."],
    examplePrompts: ["Create an SOP from this process.", "Update the project page with today's progress.", "Build a research database from this dossier."],
    setupSteps: ["Connect your Notion account.", "Choose workspace/pages.", "Discover database tools.", "Set approval rules for edits."],
    requiredUserInputs: [{ key: "oauth", label: "Notion account", type: "oauth", required: true, help: "Connect Notion through Dobly-hosted setup." }],
    capabilities: caps("document knowledge memory project admin"),
    defaultRisk: "medium",
    approvalPolicies: [
      { action: "read_pages", description: "Read pages/databases.", riskLevel: "low", approvalRequired: false, rollbackSupport: "not_available" },
      { action: "create_page", description: "Create new pages.", riskLevel: "medium", approvalRequired: false, rollbackSupport: "manual" },
      { action: "edit_existing", description: "Edit existing important records.", riskLevel: "medium", approvalRequired: true, rollbackSupport: "manual" },
    ],
    permissionScopes: ["Read pages", "Create pages", "Update selected databases", "Edit after approval"],
    sandbox: { available: true, defaultMode: "draft_only", notes: "Create draft pages first when changing important docs." },
    artifactSupport: ["document", "json", "external_link"],
    rollbackSupport: "manual",
  },
  ...[
    standbyConnector({
      id: "jira_oauth",
      label: "Jira",
      provider: "jira",
      category: "engineering",
      description: "Let Engineering and Product Operators inspect issues, create tickets, triage bugs, and coordinate releases.",
      enables: ["Read projects and issues.", "Create bug and feature tickets.", "Prepare sprint/release updates.", "Update issue state after approval."],
      prompts: ["Turn this customer complaint into Jira tickets.", "Find blockers in the current sprint.", "Draft release notes from completed work."],
      capabilityText: "jira issue bug engineering project task release",
      risk: "medium",
      scopes: ["Read projects", "Create issues", "Comment", "Update issues after approval", "Create release reports"],
    }),
    standbyConnector({
      id: "confluence_oauth",
      label: "Confluence",
      provider: "confluence",
      category: "documents",
      description: "Let Operators read, summarize, create, and update team docs, specs, SOPs, and knowledge bases.",
      enables: ["Read documentation.", "Create specs and SOPs.", "Summarize knowledge bases.", "Update docs after approval."],
      prompts: ["Create a product spec from this chat.", "Summarize the onboarding docs.", "Update the release notes after approval."],
      capabilityText: "confluence document knowledge spec project",
      risk: "medium",
      scopes: ["Read spaces", "Create pages", "Comment", "Update pages after approval"],
    }),
    standbyConnector({
      id: "gitlab_oauth",
      label: "GitLab",
      provider: "gitlab",
      category: "code",
      description: "Let Engineering Operators inspect repos, issues, pipelines, merge requests, and release context.",
      enables: ["Read repositories and issues.", "Inspect CI pipelines.", "Draft merge requests.", "Prepare release notes."],
      prompts: ["Investigate failing GitLab pipelines.", "Draft a merge request for this fix.", "Summarize open security issues."],
      capabilityText: "gitlab code repository issue ci pipeline release engineering",
      risk: "high",
      scopes: ["Read repositories", "Read issues", "Read pipelines", "Draft changes", "Open merge requests after approval"],
    }),
    standbyConnector({
      id: "bitbucket_oauth",
      label: "Bitbucket",
      provider: "bitbucket",
      category: "code",
      description: "Let Operators inspect Bitbucket repos, pull requests, issues, and build status.",
      enables: ["Read repos and pull requests.", "Inspect builds.", "Draft code review summaries.", "Prepare pull request changes."],
      prompts: ["Review this PR and summarize risks.", "Find failed builds.", "Draft a bugfix branch plan."],
      capabilityText: "bitbucket code repository pull request pipeline engineering",
      risk: "high",
      scopes: ["Read repositories", "Read pull requests", "Read builds", "Draft changes", "Open PRs after approval"],
    }),
    standbyConnector({
      id: "vercel_oauth",
      label: "Vercel",
      provider: "vercel",
      category: "engineering",
      description: "Let Operators monitor deployments, logs, domains, environment status, and release health.",
      enables: ["Read deployments and logs.", "Monitor failed builds.", "Prepare rollback recommendations.", "Coordinate production releases."],
      prompts: ["Check why the deployment failed.", "Summarize production errors after deploy.", "Prepare a rollback recommendation."],
      capabilityText: "vercel deployment logs engineering code website",
      risk: "high",
      scopes: ["Read projects", "Read deployments", "Read logs", "Trigger deploy after approval", "Rollback after approval"],
    }),
    standbyConnector({
      id: "netlify_oauth",
      label: "Netlify",
      provider: "netlify",
      category: "engineering",
      description: "Let Operators monitor Netlify sites, builds, deploy previews, forms, and release status.",
      enables: ["Read build logs.", "Monitor deploy previews.", "Summarize form submissions.", "Prepare site release actions."],
      prompts: ["Check why this Netlify build failed.", "Summarize form leads from the website.", "Prepare a deploy rollback plan."],
      capabilityText: "netlify deployment website forms logs engineering",
      risk: "high",
      scopes: ["Read sites", "Read deploys", "Read forms", "Trigger deploy after approval", "Rollback after approval"],
    }),
    standbyConnector({
      id: "cloudflare_oauth",
      label: "Cloudflare",
      provider: "cloudflare",
      category: "engineering",
      description: "Let Operators inspect DNS, domains, workers, security events, cache, and edge configuration.",
      enables: ["Read DNS and domain status.", "Monitor security events.", "Prepare cache or worker changes.", "Escalate production risks."],
      prompts: ["Check if DNS is configured correctly.", "Summarize security events overnight.", "Prepare a cache purge but ask before running it."],
      capabilityText: "cloudflare dns domain security website worker engineering",
      risk: "high",
      scopes: ["Read zones", "Read DNS", "Read security events", "Prepare changes", "Apply after approval"],
    }),
    standbyConnector({
      id: "aws_oauth",
      label: "AWS",
      provider: "aws",
      kind: "custom_api",
      category: "engineering",
      description: "Let Operators inspect AWS infrastructure, costs, logs, queues, storage, and operational health through a secure bridge.",
      enables: ["Read infrastructure status.", "Summarize costs and logs.", "Prepare infrastructure changes.", "Escalate production incidents."],
      prompts: ["Find abnormal AWS spend.", "Summarize Lambda errors.", "Prepare an S3 lifecycle policy but ask before applying."],
      capabilityText: "aws cloud infrastructure logs cost engineering operate software",
      risk: "high",
      scopes: ["Read allowed services", "Read logs", "Read cost data", "Prepare changes", "Apply after approval"],
    }),
    standbyConnector({
      id: "google_cloud_oauth",
      label: "Google Cloud",
      provider: "google_cloud",
      kind: "custom_api",
      category: "engineering",
      description: "Let Operators inspect GCP projects, logs, billing, deployments, storage, and operational signals.",
      enables: ["Read cloud logs and metrics.", "Summarize billing.", "Prepare deployment actions.", "Escalate infrastructure risks."],
      prompts: ["Find GCP errors from the last hour.", "Summarize cloud spend changes.", "Prepare a deploy checklist."],
      capabilityText: "gcp google cloud infrastructure logs cost engineering",
      risk: "high",
      scopes: ["Read projects", "Read logs", "Read billing", "Prepare changes", "Apply after approval"],
    }),
    standbyConnector({
      id: "azure_oauth",
      label: "Azure",
      provider: "azure",
      kind: "custom_api",
      category: "engineering",
      description: "Let Operators inspect Azure resources, logs, costs, app services, and operational health.",
      enables: ["Read resource health.", "Monitor logs and cost.", "Prepare cloud changes.", "Escalate production issues."],
      prompts: ["Summarize Azure app errors.", "Find abnormal spend.", "Prepare a scaling recommendation."],
      capabilityText: "azure cloud infrastructure logs cost engineering",
      risk: "high",
      scopes: ["Read resources", "Read logs", "Read costs", "Prepare changes", "Apply after approval"],
    }),
    standbyConnector({
      id: "datadog_oauth",
      label: "Datadog",
      provider: "datadog",
      category: "engineering",
      description: "Let Operators monitor observability signals, dashboards, logs, incidents, and service health.",
      enables: ["Read metrics and logs.", "Summarize incidents.", "Create incident reports.", "Trigger follow-up engineering tasks."],
      prompts: ["Explain why latency spiked.", "Summarize incidents from today.", "Create tasks from recurring alerts."],
      capabilityText: "datadog logs metrics monitoring incident engineering",
      risk: "medium",
      scopes: ["Read metrics", "Read logs", "Read dashboards", "Create reports", "Create tasks after approval"],
    }),
    standbyConnector({
      id: "pagerduty_oauth",
      label: "PagerDuty",
      provider: "pagerduty",
      category: "engineering",
      description: "Let Operators monitor incidents, on-call context, escalations, and postmortem follow-up.",
      enables: ["Read incidents.", "Summarize on-call activity.", "Draft postmortems.", "Escalate urgent issues."],
      prompts: ["Summarize incidents overnight.", "Draft a postmortem from this incident.", "Tell me what is still unresolved."],
      capabilityText: "pagerduty incident oncall engineering support",
      risk: "high",
      scopes: ["Read incidents", "Read on-call", "Draft postmortems", "Escalate after approval", "Resolve after approval"],
    }),
    standbyConnector({
      id: "docker_hub_oauth",
      label: "Docker Hub",
      provider: "docker_hub",
      category: "engineering",
      description: "Let Operators inspect images, repositories, tags, and release artifacts.",
      enables: ["Read image repositories.", "Inspect tags and metadata.", "Prepare release notes.", "Flag stale or vulnerable images."],
      prompts: ["Find stale Docker images.", "Summarize latest image tags.", "Prepare a release checklist."],
      capabilityText: "docker container image release engineering",
      risk: "medium",
      scopes: ["Read repos", "Read tags", "Create reports", "Push after approval"],
    }),
    standbyConnector({
      id: "terraform_cloud_oauth",
      label: "Terraform Cloud",
      provider: "terraform_cloud",
      category: "engineering",
      description: "Let Operators inspect workspaces, plans, runs, drift, and infrastructure change proposals.",
      enables: ["Read Terraform workspaces.", "Summarize plans and drift.", "Prepare infrastructure change reviews.", "Ask before applies."],
      prompts: ["Summarize this Terraform plan.", "Find drift across workspaces.", "Prepare apply notes but ask before applying."],
      capabilityText: "terraform infrastructure cloud engineering deploy",
      risk: "high",
      scopes: ["Read workspaces", "Read plans", "Create reports", "Queue runs after approval", "Apply after approval"],
    }),
    standbyConnector({
      id: "kubernetes_bridge",
      label: "Kubernetes",
      provider: "kubernetes",
      kind: "custom_api",
      category: "engineering",
      description: "Let Operators inspect Kubernetes clusters through a secure bridge and prepare operational actions.",
      enables: ["Read pods, deployments, and events.", "Summarize cluster health.", "Prepare rollout or rollback actions.", "Escalate production risks."],
      prompts: ["Why are pods crashing?", "Summarize cluster health.", "Prepare a rollback but ask before running it."],
      capabilityText: "kubernetes cluster pods deployment logs engineering",
      risk: "high",
      scopes: ["Read namespaces", "Read logs", "Read events", "Prepare changes", "Apply after approval"],
    }),
    standbyConnector({
      id: "clickup_oauth",
      label: "ClickUp",
      provider: "clickup",
      category: "personal",
      description: "Let Operators manage tasks, docs, projects, statuses, and team follow-up in ClickUp.",
      enables: ["Read tasks and projects.", "Create tasks.", "Draft status updates.", "Move work after approval."],
      prompts: ["Turn this meeting into ClickUp tasks.", "Find overdue tasks.", "Prepare my weekly project update."],
      capabilityText: "clickup task project document status productivity",
      risk: "medium",
      scopes: ["Read spaces", "Create tasks", "Comment", "Update after approval", "Assign after approval"],
    }),
    standbyConnector({
      id: "monday_oauth",
      label: "monday.com",
      provider: "monday",
      category: "personal",
      description: "Let Operators manage boards, items, owners, statuses, timelines, and operating rhythms in monday.com.",
      enables: ["Read boards.", "Create items.", "Prepare status updates.", "Update work after approval."],
      prompts: ["Create monday.com items from this plan.", "Find delayed work.", "Summarize board changes this week."],
      capabilityText: "monday task project board productivity status",
      risk: "medium",
      scopes: ["Read boards", "Create items", "Comment", "Update after approval", "Assign after approval"],
    }),
    standbyConnector({
      id: "todoist_oauth",
      label: "Todoist",
      provider: "todoist",
      category: "personal",
      description: "Let Personal and Admin Operators manage tasks, reminders, recurring duties, and personal open loops.",
      enables: ["Read tasks.", "Create reminders.", "Organize personal work.", "Run recurring personal loops."],
      prompts: ["Turn this into Todoist tasks.", "Remind me before renewals.", "Organize my errands for the week."],
      capabilityText: "todoist task reminder personal productivity",
      risk: "medium",
      scopes: ["Read tasks", "Create tasks", "Create reminders", "Complete after approval"],
    }),
    standbyConnector({
      id: "coda_oauth",
      label: "Coda",
      provider: "coda",
      category: "documents",
      description: "Let Operators read, create, update, and report from Coda docs and tables.",
      enables: ["Read docs and tables.", "Create docs.", "Update rows after approval.", "Generate operating reports."],
      prompts: ["Update the operating dashboard.", "Create a Coda doc from this plan.", "Summarize table changes this week."],
      capabilityText: "coda document table spreadsheet project productivity",
      risk: "medium",
      scopes: ["Read docs", "Read tables", "Create docs", "Update rows after approval"],
    }),
    standbyConnector({
      id: "miro_oauth",
      label: "Miro",
      provider: "miro",
      category: "design",
      description: "Let Operators create whiteboard drafts, map processes, summarize boards, and prepare collaboration artifacts.",
      enables: ["Read boards.", "Create whiteboard drafts.", "Map processes.", "Attach board summaries."],
      prompts: ["Turn this strategy into a Miro board.", "Summarize this workshop board.", "Create a customer journey map."],
      capabilityText: "miro design whiteboard document project",
      risk: "medium",
      scopes: ["Read boards", "Create boards", "Add items", "Edit after approval"],
    }),
    standbyConnector({
      id: "box_oauth",
      label: "Box",
      provider: "box",
      category: "documents",
      description: "Let Operators find, summarize, organize, and store documents in Box with approval controls.",
      enables: ["Read selected folders.", "Summarize files.", "Upload artifacts.", "Move/share files after approval."],
      prompts: ["Find the latest legal document.", "Summarize this Box folder.", "Upload the approved proposal."],
      capabilityText: "box file document folder storage",
      risk: "medium",
      scopes: ["Read selected folders", "Upload artifacts", "Create folders", "Move/share after approval"],
    }),
    standbyConnector({
      id: "coinbase_oauth",
      label: "Coinbase",
      provider: "coinbase",
      category: "finance",
      description: "Let Market Watch Operators monitor Coinbase portfolios, crypto prices, balances, and strategy drift without trading by default.",
      enables: ["Read portfolio balances.", "Monitor crypto prices.", "Track strategy signals.", "Escalate trade recommendations for approval."],
      prompts: ["Watch my BTC and ETH strategy.", "Tell me if my crypto allocation drifts.", "Alert me when my exit rule triggers."],
      capabilityText: "coinbase crypto market price portfolio finance monitor_market",
      risk: "high",
      scopes: ["Read balances", "Read prices", "Read transactions", "Prepare trade alerts", "Trade only after approval"],
    }),
    standbyConnector({
      id: "kalshi_oauth",
      label: "Kalshi",
      provider: "kalshi",
      category: "finance",
      description: "Let Market Watch Operators monitor prediction markets, watch lists, prices, and strategy triggers with approval gates.",
      enables: ["Monitor prediction markets.", "Track watchlists.", "Alert on price or probability changes.", "Prepare strategy reports."],
      prompts: ["Watch these Kalshi markets and alert me at my trigger.", "Summarize markets moving today.", "Tell me when my strategy changes."],
      capabilityText: "kalshi market prediction price finance monitor_market",
      risk: "high",
      scopes: ["Read markets", "Read watchlists", "Read balances", "Prepare alerts", "Trade only after approval"],
    }),
    standbyConnector({
      id: "spotify_oauth",
      label: "Spotify",
      provider: "spotify",
      category: "personal",
      description: "Let Personal and Creator Operators manage playlists, listening context, podcast research, and music workflows.",
      enables: ["Read playlists and listening context.", "Create playlist drafts.", "Research music/podcast patterns.", "Prepare personal or creator automations."],
      prompts: ["Create a focus playlist for my workday.", "Track podcast episodes I should listen to.", "Make a playlist for my brand event."],
      capabilityText: "spotify music podcast playlist personal research",
      risk: "medium",
      scopes: ["Read playlists", "Create playlists", "Edit playlists after approval", "Read listening context"],
    }),
    standbyConnector({
      id: "zendesk_oauth",
      label: "Zendesk",
      provider: "zendesk",
      category: "communication",
      description: "Let Support Operators triage tickets, draft replies, summarize issues, and escalate customer problems.",
      enables: ["Read support tickets.", "Draft customer replies.", "Summarize recurring issues.", "Escalate high-risk cases."],
      prompts: ["Summarize angry tickets from today.", "Draft replies for refund requests.", "Escalate tickets that need me."],
      capabilityText: "zendesk support ticket customer message",
      risk: "high",
      scopes: ["Read tickets", "Draft replies", "Send after approval", "Update status after approval"],
    }),
    standbyConnector({
      id: "intercom_oauth",
      label: "Intercom",
      provider: "intercom",
      category: "communication",
      description: "Let Operators handle live chat, inbox conversations, customer follow-ups, and support insights.",
      enables: ["Read inbox conversations.", "Draft chat replies.", "Route high-value customers.", "Extract support insights."],
      prompts: ["Watch Intercom and escalate urgent customers.", "Draft replies for common questions.", "Summarize complaints this week."],
      capabilityText: "intercom support chat customer message",
      risk: "high",
      scopes: ["Read inbox", "Draft replies", "Send after approval", "Update contacts after approval"],
    }),
    standbyConnector({
      id: "freshdesk_oauth",
      label: "Freshdesk",
      provider: "freshdesk",
      category: "communication",
      description: "Let Support Operators triage tickets, draft responses, update status, and report support trends.",
      enables: ["Read support tickets.", "Draft responses.", "Detect recurring issues.", "Prepare support reports."],
      prompts: ["Find tickets waiting more than 24 hours.", "Draft simple responses.", "Show this week's support themes."],
      capabilityText: "freshdesk support ticket customer message",
      risk: "high",
      scopes: ["Read tickets", "Draft responses", "Send after approval", "Close after approval"],
    }),
    standbyConnector({
      id: "mailchimp_oauth",
      label: "Mailchimp",
      provider: "mailchimp",
      category: "communication",
      description: "Let Growth Operators draft newsletters, segment audiences, monitor email performance, and ask before sending.",
      enables: ["Draft email campaigns.", "Segment audiences.", "Prepare newsletters.", "Analyze campaign performance."],
      prompts: ["Create this week's newsletter draft.", "Segment leads by engagement.", "Summarize campaign performance."],
      capabilityText: "mailchimp email campaign marketing message publish",
      risk: "high",
      scopes: ["Read audiences", "Draft campaigns", "Read analytics", "Send after approval"],
    }),
    standbyConnector({
      id: "klaviyo_oauth",
      label: "Klaviyo",
      provider: "klaviyo",
      category: "commerce",
      description: "Let ecommerce Growth Operators draft lifecycle campaigns, segments, flows, and performance reports.",
      enables: ["Draft lifecycle campaigns.", "Analyze ecommerce email performance.", "Suggest segments.", "Prepare flows."],
      prompts: ["Draft an abandoned cart flow.", "Find segments with falling engagement.", "Create a product launch email package."],
      capabilityText: "klaviyo email campaign ecommerce marketing publish",
      risk: "high",
      scopes: ["Read lists", "Read metrics", "Draft campaigns", "Draft flows", "Activate after approval"],
    }),
    standbyConnector({
      id: "paypal_oauth",
      label: "PayPal",
      provider: "paypal",
      category: "finance",
      description: "Let Finance Operators inspect payments, prepare invoices, watch disputes, and ask before money movement.",
      enables: ["Read transactions.", "Prepare invoices.", "Monitor disputes.", "Escalate refunds and payment issues."],
      prompts: ["Find disputed payments and summarize risk.", "Prepare a PayPal invoice.", "Report this week's PayPal revenue."],
      capabilityText: "paypal payment invoice finance charge",
      risk: "high",
      scopes: ["Read transactions", "Read disputes", "Draft invoices", "Refund after approval"],
    }),
    standbyConnector({
      id: "woocommerce_oauth",
      label: "WooCommerce",
      provider: "woocommerce",
      category: "commerce",
      description: "Let Commerce Operators inspect orders, products, customers, refunds, and inventory.",
      enables: ["Track orders.", "Monitor inventory.", "Prepare product updates.", "Draft customer updates."],
      prompts: ["Find delayed orders.", "Prepare product listing improvements.", "Summarize purchase trends."],
      capabilityText: "woocommerce ecommerce commerce order inventory customer",
      risk: "high",
      scopes: ["Read orders", "Read products", "Draft updates", "Write after approval", "Refund after approval"],
    }),
    standbyConnector({
      id: "amazon_seller_oauth",
      label: "Amazon Seller Central",
      provider: "amazon_seller",
      category: "commerce",
      description: "Let Commerce Operators inspect Amazon orders, listings, inventory, reviews, and seller performance signals.",
      enables: ["Monitor orders and inventory.", "Draft listing improvements.", "Summarize reviews.", "Alert on seller issues."],
      prompts: ["Find listings losing conversion.", "Summarize negative reviews.", "Alert me when inventory risk appears."],
      capabilityText: "amazon seller commerce order inventory product research",
      risk: "high",
      scopes: ["Read orders", "Read inventory", "Read reviews", "Draft listing updates", "Update after approval"],
    }),
    standbyConnector({
      id: "webflow_oauth",
      label: "Webflow",
      provider: "webflow",
      category: "design",
      description: "Let Operators update CMS drafts, prepare landing pages, inspect forms, and publish Webflow changes after approval.",
      enables: ["Create CMS drafts.", "Prepare landing page content.", "Inspect form submissions.", "Publish approved updates."],
      prompts: ["Draft a landing page from this offer.", "Update CMS posts after approval.", "Summarize new Webflow leads."],
      capabilityText: "webflow website design document publish form",
      risk: "high",
      scopes: ["Read site", "Read forms", "Create drafts", "Publish after approval"],
    }),
    standbyConnector({
      id: "wordpress_oauth",
      label: "WordPress",
      provider: "wordpress",
      category: "documents",
      description: "Let Operators draft posts, manage pages, summarize comments, and publish WordPress content after approval.",
      enables: ["Draft blog posts.", "Update pages after approval.", "Moderate comments.", "Attach SEO reports."],
      prompts: ["Turn this research into a WordPress draft.", "Update the FAQ page.", "Summarize comments that need replies."],
      capabilityText: "wordpress blog document publish website",
      risk: "high",
      scopes: ["Read content", "Create drafts", "Moderate after approval", "Publish after approval"],
    }),
    standbyConnector({
      id: "typeform_oauth",
      label: "Typeform",
      provider: "typeform",
      category: "data",
      description: "Let Operators read form responses, summarize submissions, create form drafts, and trigger follow-up loops.",
      enables: ["Read responses.", "Summarize leads and surveys.", "Draft new forms.", "Route submissions to Operators."],
      prompts: ["Summarize this week's Typeform leads.", "Create a customer intake form.", "Route urgent responses."],
      capabilityText: "typeform form survey lead data crm",
      risk: "medium",
      scopes: ["Read responses", "Create form drafts", "Publish after approval", "Edit after approval"],
    }),
    standbyConnector({
      id: "apollo_oauth",
      label: "Apollo",
      provider: "apollo",
      category: "crm",
      description: "Let Sales Operators find prospects, enrich leads, prepare lists, and route outreach through approval rules.",
      enables: ["Search prospects.", "Enrich leads.", "Create target lists.", "Prepare outbound campaigns."],
      prompts: ["Find 500 qualified leads matching this ICP.", "Enrich this lead list.", "Prepare outreach drafts."],
      capabilityText: "apollo lead prospect crm sales email research",
      risk: "high",
      scopes: ["Search prospects", "Enrich leads", "Create lists", "Export after approval"],
    }),
    standbyConnector({
      id: "zoominfo_oauth",
      label: "ZoomInfo",
      provider: "zoominfo",
      category: "crm",
      description: "Let Sales Operators research accounts, enrich contacts, build prospect lists, and monitor buying signals.",
      enables: ["Enrich accounts.", "Build prospect lists.", "Monitor intent signals.", "Feed CRM updates after approval."],
      prompts: ["Find accounts showing intent.", "Enrich these contacts.", "Create a target account list."],
      capabilityText: "zoominfo lead prospect crm sales research",
      risk: "high",
      scopes: ["Search accounts", "Enrich contacts", "Read intent", "Export after approval"],
    }),
    standbyConnector({
      id: "google_analytics_oauth",
      label: "Google Analytics",
      provider: "google_analytics",
      category: "data",
      description: "Let Growth Operators read analytics, monitor funnels, report conversion changes, and trigger recommendations.",
      enables: ["Read traffic and conversion data.", "Detect funnel changes.", "Generate analytics reports.", "Trigger growth recommendations."],
      prompts: ["Tell me what changed in traffic.", "Find pages with falling conversion.", "Prepare a monthly analytics report."],
      capabilityText: "google analytics data research report website",
      risk: "low",
      scopes: ["Read properties", "Read reports", "Create reports", "Change settings after approval"],
    }),
    standbyConnector({
      id: "google_ads_oauth",
      label: "Google Ads",
      provider: "google_ads",
      category: "data",
      description: "Let Growth Operators inspect campaigns, draft ads, monitor spend, and ask before budget changes.",
      enables: ["Read campaign performance.", "Draft ad copy.", "Flag spend anomalies.", "Prepare campaign changes."],
      prompts: ["Find campaigns wasting spend.", "Draft new search ads.", "Prepare budget changes for approval."],
      capabilityText: "google ads marketing campaign analytics publish",
      risk: "high",
      scopes: ["Read campaigns", "Read spend", "Draft ads", "Apply changes after approval"],
    }),
    standbyConnector({
      id: "meta_ads_oauth",
      label: "Meta Ads",
      provider: "meta_ads",
      category: "data",
      description: "Let Growth Operators inspect Meta campaigns, draft creatives, monitor spend, and ask before live changes.",
      enables: ["Read ad performance.", "Draft creative variants.", "Detect spend anomalies.", "Prepare campaign changes."],
      prompts: ["Find Meta ads with poor ROAS.", "Draft new creative angles.", "Pause losers only after approval."],
      capabilityText: "meta ads facebook instagram marketing campaign analytics",
      risk: "high",
      scopes: ["Read campaigns", "Read spend", "Draft creatives", "Apply changes after approval"],
    }),
    standbyConnector({
      id: "postgres_database",
      label: "PostgreSQL",
      provider: "postgres",
      kind: "custom_api",
      category: "data",
      description: "Let Operators query approved Postgres data sources through a controlled database bridge.",
      enables: ["Run read-only business queries.", "Generate reports.", "Power dashboards.", "Prepare write scripts for approval."],
      prompts: ["Show customers with falling usage.", "Generate a revenue cohort report.", "Prepare this data fix but do not run it."],
      capabilityText: "postgres sql database data spreadsheet report",
      risk: "high",
      scopes: ["Read allowed schemas", "Create reports", "Prepare write scripts", "Run writes after approval"],
    }),
    standbyConnector({
      id: "snowflake_oauth",
      label: "Snowflake",
      provider: "snowflake",
      kind: "custom_api",
      category: "data",
      description: "Let Data Operators query approved Snowflake datasets and generate reports through a controlled bridge.",
      enables: ["Query warehouse data.", "Generate business reports.", "Detect anomalies.", "Prepare analysis artifacts."],
      prompts: ["Find revenue anomalies.", "Create a retention report.", "Compare this month against last month."],
      capabilityText: "snowflake data analytics database report",
      risk: "medium",
      scopes: ["Read approved datasets", "Create reports", "Respect query limits", "Run high-cost queries after approval"],
    }),
    standbyConnector({
      id: "supabase_oauth_mcp",
      label: "Supabase",
      provider: "supabase",
      kind: "mcp",
      category: "engineering",
      description: "Let Engineering Operators inspect Supabase projects, schemas, logs, and database context through MCP.",
      enables: ["Inspect schemas and logs.", "Draft migrations.", "Review database changes.", "Attach SQL artifacts."],
      prompts: ["Inspect this table.", "Draft a migration but do not run it.", "Summarize auth errors from logs."],
      capabilityText: "supabase database code engineering logs",
      risk: "high",
      scopes: ["Read schema", "Read logs", "Draft SQL", "Apply after approval"],
    }),
    standbyConnector({
      id: "sentry_oauth",
      label: "Sentry",
      provider: "sentry",
      category: "engineering",
      description: "Let Engineering Operators monitor errors, summarize incidents, connect issues to code, and prepare bug reports.",
      enables: ["Read errors and releases.", "Summarize incidents.", "Draft bug tickets.", "Trigger engineering loops."],
      prompts: ["Summarize new production errors.", "Find the most damaging issue.", "Create Linear issues from top crashes."],
      capabilityText: "sentry error bug engineering issue code",
      risk: "medium",
      scopes: ["Read issues", "Read releases", "Create bug reports", "Resolve after approval"],
    }),
  ],
];

export function listUniversalConnectorDefinitions() {
  return UNIVERSAL_CONNECTOR_CATALOG;
}

export function getUniversalConnectorDefinition(id: string) {
  return UNIVERSAL_CONNECTOR_CATALOG.find((connector) => connector.id === id) ?? null;
}
