export const TELEMETRY_EVENTS = [
  "signup_completed",
  "onboarding_started",
  "onboarding_step_completed",
  "onboarding_completed",
  "workspace_created",
  "workspace_search_used",
  "coworker_created",
  "coworker_message_sent",
  "first_run_started",
  "runtime_task_completed",
  "runtime_task_failed",
  "first_success",
  "connection_started",
  "connection_completed",
  "approval_decided",
  "checkout_started",
  "subscription_activated",
  "subscription_cancelled",
  "subscription_payment_failed",
  "user_reactivated",
  "department_launched",
  "report_exported",
  "help_opened",
  "web_vital",
  "frontend_error",
  "provider_request_completed",
] as const;

export type TelemetryEventName = (typeof TELEMETRY_EVENTS)[number];

export const TELEMETRY_EVENT_VERSION = 1;

export const TELEMETRY_EVENT_OWNERS: Record<TelemetryEventName, "growth" | "product" | "runtime" | "billing" | "reliability"> = {
  signup_completed: "growth",
  onboarding_started: "product",
  onboarding_step_completed: "product",
  onboarding_completed: "product",
  workspace_created: "product",
  workspace_search_used: "product",
  coworker_created: "product",
  coworker_message_sent: "product",
  first_run_started: "runtime",
  runtime_task_completed: "runtime",
  runtime_task_failed: "reliability",
  first_success: "product",
  connection_started: "product",
  connection_completed: "product",
  approval_decided: "runtime",
  checkout_started: "billing",
  subscription_activated: "billing",
  subscription_cancelled: "billing",
  subscription_payment_failed: "billing",
  user_reactivated: "growth",
  department_launched: "product",
  report_exported: "product",
  help_opened: "product",
  web_vital: "reliability",
  frontend_error: "reliability",
  provider_request_completed: "reliability",
};
