import type {
  OfficeDepartmentDefinition,
  OfficeDepartmentId,
  OfficeEventType,
  OfficeWorkerDefinition,
  OfficeWorkerKind,
} from "@/lib/office/types";

export const OFFICE_DEPARTMENTS: OfficeDepartmentDefinition[] = [
  {
    id: "reception",
    name: "Reception",
    purpose: "Owns inbound conversations, routing, lead capture, and front-door response quality across channels around the clock.",
    coreWorkerKinds: ["bot", "agent", "automation"],
    eventTypes: ["message.received", "message.draft_created", "message.sent", "lead.created"],
    defaultMetrics: ["first_response_time", "unanswered_messages", "qualified_leads"],
    launchPriority: 1,
  },
  {
    id: "marketing",
    name: "Marketing",
    purpose: "Plans, drafts, publishes, repurposes, and learns from content and social activity like a nonstop creative desk.",
    coreWorkerKinds: ["agent", "automation", "bot"],
    eventTypes: [
      "content.idea_received",
      "content.draft_created",
      "content.scheduled",
      "content.published",
      "content.performance_synced",
    ],
    defaultMetrics: ["posts_scheduled", "engagement_rate", "content_leads"],
    launchPriority: 2,
  },
  {
    id: "creative",
    name: "Creative & Design",
    purpose: "Turns ideas into designs, decks, videos, brand assets, creative variants, and production-ready deliverables.",
    coreWorkerKinds: ["agent", "automation"],
    eventTypes: ["content.idea_received", "content.draft_created", "worker.action_proposed", "briefing.created"],
    defaultMetrics: ["assets_in_progress", "decks_created", "creative_reviews"],
    launchPriority: 3,
  },
  {
    id: "sales",
    name: "Sales",
    purpose: "Tracks leads, pipeline movement, proposals, follow-ups, and deal conversion with persistent multi-step chase loops.",
    coreWorkerKinds: ["agent", "automation"],
    eventTypes: ["lead.created", "lead.qualified", "message.sent"],
    defaultMetrics: ["new_leads", "qualified_leads", "followups_due"],
    launchPriority: 4,
  },
  {
    id: "finance",
    name: "Finance",
    purpose: "Tracks invoices, payments, M-PESA reconciliation, expenses, and cash risk while staying approval-gated for any money-impacting action.",
    coreWorkerKinds: ["automation", "agent"],
    eventTypes: ["invoice.created", "invoice.overdue", "payment.received", "payment.reconciled"],
    defaultMetrics: ["overdue_amount", "payments_received", "reconciliation_gaps"],
    launchPriority: 5,
  },
  {
    id: "support",
    name: "Support",
    purpose: "Owns tickets, complaints, refunds, knowledge-base answers, and customer recovery with 24/7 triage coverage.",
    coreWorkerKinds: ["bot", "agent", "automation"],
    eventTypes: ["support.ticket_created", "support.ticket_resolved", "message.received"],
    defaultMetrics: ["open_tickets", "resolution_time", "escalations"],
    launchPriority: 6,
  },
  {
    id: "engineering",
    name: "Engineering & Product",
    purpose: "Converts feedback, bugs, releases, QA checks, specs, and product decisions into clear technical execution.",
    coreWorkerKinds: ["agent", "automation"],
    eventTypes: ["worker.action_proposed", "worker.action_executed", "signal.detected", "briefing.created"],
    defaultMetrics: ["issues_packaged", "release_risks", "qa_checks"],
    launchPriority: 7,
  },
  {
    id: "operations",
    name: "Operations",
    purpose: "Keeps orders, suppliers, fulfillment, inventory, and internal processes moving through persistent coordination.",
    coreWorkerKinds: ["automation", "agent"],
    eventTypes: ["operations.order_created", "operations.fulfillment_updated"],
    defaultMetrics: ["open_orders", "fulfillment_delays", "supplier_issues"],
    launchPriority: 8,
  },
  {
    id: "admin",
    name: "Admin",
    purpose: "Handles calendar coordination, reminders, internal records, and recurring admin work like an infinite executive assistant.",
    coreWorkerKinds: ["automation", "agent"],
    eventTypes: ["worker.action_proposed", "worker.action_executed"],
    defaultMetrics: ["tasks_completed", "appointments_booked", "documents_updated"],
    launchPriority: 9,
  },
  {
    id: "projects",
    name: "Projects",
    purpose: "Tracks client projects, deadlines, deliverables, approvals, dependencies, and handoffs end to end.",
    coreWorkerKinds: ["agent", "automation"],
    eventTypes: ["worker.action_proposed", "worker.action_executed"],
    defaultMetrics: ["active_projects", "blocked_deliverables", "approvals_due"],
    launchPriority: 10,
  },
  {
    id: "hr",
    name: "HR",
    purpose: "Supports onboarding, leave, internal requests, team tasks, and performance follow-through with auditability.",
    coreWorkerKinds: ["automation", "agent"],
    eventTypes: ["worker.action_proposed", "worker.action_executed"],
    defaultMetrics: ["open_people_tasks", "onboarding_steps", "leave_requests"],
    launchPriority: 11,
  },
  {
    id: "growth",
    name: "Growth",
    purpose: "Runs experiments, partnerships, competitor tracking, and expansion opportunity discovery continuously.",
    coreWorkerKinds: ["agent", "automation"],
    eventTypes: ["signal.detected", "content.performance_synced"],
    defaultMetrics: ["experiments_running", "opportunities_found", "partnerships_active"],
    launchPriority: 12,
  },
  {
    id: "analytics",
    name: "Analytics",
    purpose: "Turns events and metrics into patterns, anomalies, briefings, and trend explanations before humans have to ask.",
    coreWorkerKinds: ["agent", "automation"],
    eventTypes: ["signal.detected", "briefing.created"],
    defaultMetrics: ["open_anomalies", "reports_generated", "metrics_watched"],
    launchPriority: 13,
  },
  {
    id: "compliance",
    name: "Compliance",
    purpose: "Owns privacy, audit trails, consent records, and high-risk approval policies as an always-on policy watchdog.",
    coreWorkerKinds: ["automation", "agent"],
    eventTypes: ["worker.action_proposed", "integration.failed"],
    defaultMetrics: ["audit_events", "high_risk_actions", "policy_exceptions"],
    launchPriority: 14,
  },
  {
    id: "integrations",
    name: "Integrations",
    purpose: "Watches connection health, webhooks, credentials, API limits, and sync quality.",
    coreWorkerKinds: ["automation"],
    eventTypes: ["integration.connected", "integration.failed"],
    defaultMetrics: ["healthy_connections", "failed_syncs", "rate_limit_events"],
    launchPriority: 15,
    isSpecialRoom: true,
  },
  {
    id: "training_room",
    name: "Training Room",
    purpose: "Stores brand voice, business knowledge, policies, examples, and coworker feedback.",
    coreWorkerKinds: ["agent"],
    eventTypes: ["worker.action_approved", "worker.action_rejected"],
    defaultMetrics: ["knowledge_items", "feedback_examples", "tests_passed"],
    launchPriority: 16,
    isSpecialRoom: true,
  },
  {
    id: "filing_cabinet",
    name: "Filing Cabinet",
    purpose: "Stores people, messages, documents, transactions, tasks, events, and searchable memory.",
    coreWorkerKinds: ["automation", "agent"],
    eventTypes: ["message.received", "payment.received", "content.published", "worker.action_executed"],
    defaultMetrics: ["records_indexed", "documents_stored", "memory_items"],
    launchPriority: 17,
    isSpecialRoom: true,
  },
  {
    id: "general_manager",
    name: "General Manager",
    purpose: "Monitors the whole office, synthesizes briefings, spots cross-department risks, and coordinates decisions.",
    coreWorkerKinds: ["agent"],
    eventTypes: ["signal.detected", "briefing.created", "worker.failed", "integration.failed"],
    defaultMetrics: ["briefings_created", "risks_open", "decisions_needed"],
    launchPriority: 18,
    isSpecialRoom: true,
  },
  {
    id: "boardroom",
    name: "Boardroom",
    purpose: "Runs strategic reviews across finance, marketing, operations, revenue, customer, and strategy.",
    coreWorkerKinds: ["agent"],
    eventTypes: ["briefing.created", "signal.detected"],
    defaultMetrics: ["board_reports", "strategic_questions", "recommendations"],
    launchPriority: 19,
    isSpecialRoom: true,
  },
];

export const OFFICE_WORKER_TEMPLATES: OfficeWorkerDefinition[] = [
  {
    key: "front_desk_bot",
    name: "Front Desk Bot",
    kind: "bot",
    departmentId: "reception",
    mission: "Respond quickly to inbound WhatsApp, email, chat, and social messages using approved business context.",
    defaultAutonomy: "supervised",
    requiredTools: ["whatsapp", "gmail"],
    handles: ["message.received"],
    proposes: ["Draft reply", "Route lead", "Escalate sensitive conversation"],
    neverDoes: ["Promise refunds", "Negotiate legal terms", "Share private financial data"],
  },
  {
    key: "content_writer_agent",
    name: "Content Writer Agent",
    kind: "agent",
    departmentId: "marketing",
    mission: "Turn business ideas, products, and campaign goals into channel-ready content drafts.",
    defaultAutonomy: "supervised",
    requiredTools: [],
    handles: ["content.idea_received"],
    proposes: ["Draft post", "Repurpose content", "Recommend campaign angle"],
    neverDoes: ["Publish without approval", "Invent offers", "Use unapproved claims"],
  },
  {
    key: "social_publisher_automation",
    name: "Social Publisher Automation",
    kind: "automation",
    departmentId: "marketing",
    mission: "Publish approved content on schedule and log performance when platforms report back.",
    defaultAutonomy: "guarded",
    requiredTools: ["facebook", "instagram"],
    handles: ["content.scheduled"],
    proposes: ["Publish approved post", "Retry failed publish", "Sync performance metrics"],
    neverDoes: ["Edit approved copy materially", "Publish rejected content"],
  },
  {
    key: "invoice_chaser_automation",
    name: "Invoice Chaser Automation",
    kind: "automation",
    departmentId: "finance",
    mission: "Detect overdue invoices and prepare respectful reminders through approved channels.",
    defaultAutonomy: "supervised",
    requiredTools: ["mpesa", "gmail"],
    handles: ["invoice.overdue"],
    proposes: ["Draft payment reminder", "Mark invoice for dispute review", "Escalate overdue account"],
    neverDoes: ["Apply penalties", "Change invoice amounts", "Accept payment plans without approval"],
  },
  {
    key: "payment_reconciliation_automation",
    name: "Payment Reconciliation Automation",
    kind: "automation",
    departmentId: "finance",
    mission: "Match Paystack, M-PESA, and bank payments to invoices and flag gaps.",
    defaultAutonomy: "guarded",
    requiredTools: ["mpesa"],
    handles: ["payment.received"],
    proposes: ["Match payment", "Flag mismatch", "Update invoice status"],
    neverDoes: ["Delete financial records", "Move money", "Override disputes"],
  },
  {
    key: "general_manager_agent",
    name: "General Manager Agent",
    kind: "agent",
    departmentId: "general_manager",
    mission: "Synthesize office activity into priorities, briefings, risks, and owner decisions.",
    defaultAutonomy: "supervised",
    requiredTools: [],
    handles: ["signal.detected", "worker.failed", "integration.failed", "briefing.created"],
    proposes: ["Create daily briefing", "Escalate cross-department risk", "Recommend next action"],
    neverDoes: ["Make irreversible business decisions", "Approve its own high-risk actions"],
  },
  {
    key: "website_reception_chatbot",
    name: "Website Reception Chatbot",
    kind: "bot",
    departmentId: "reception",
    mission: "Answer website visitors, capture contact details, qualify intent, and route promising leads to Sales.",
    defaultAutonomy: "supervised",
    requiredTools: ["website_chat", "crm"],
    handles: ["message.received", "lead.created"],
    proposes: ["Answer visitor question", "Capture lead", "Route to Sales", "Escalate unclear request"],
    neverDoes: ["Invent pricing", "Promise availability without checking calendar", "Handle legal or medical advice"],
  },
  {
    key: "appointment_booking_worker",
    name: "Appointment Booking Worker",
    kind: "automation",
    departmentId: "reception",
    mission: "Check availability, propose appointment slots, book meetings, and send confirmations.",
    defaultAutonomy: "guarded",
    requiredTools: ["google_calendar"],
    handles: ["lead.created", "message.received"],
    proposes: ["Book appointment", "Reschedule appointment", "Send confirmation", "Escalate calendar conflict"],
    neverDoes: ["Double-book unavailable time", "Cancel paid appointments without approval"],
  },
  {
    key: "missed_call_recovery_worker",
    name: "Missed Call Recovery Worker",
    kind: "automation",
    departmentId: "reception",
    mission: "Follow up missed calls quickly with a text, WhatsApp, or email and create a lead record.",
    defaultAutonomy: "guarded",
    requiredTools: ["sms", "whatsapp", "crm"],
    handles: ["message.received", "lead.created"],
    proposes: ["Send missed-call text", "Create lead", "Schedule callback", "Escalate VIP caller"],
    neverDoes: ["Spam repeated follow-ups", "Send marketing messages without opt-in"],
  },
  {
    key: "lead_qualification_agent",
    name: "Lead Qualification Agent",
    kind: "agent",
    departmentId: "sales",
    mission: "Qualify new leads against the business offer, urgency, budget, location, and fit rules.",
    defaultAutonomy: "supervised",
    requiredTools: ["crm", "gmail"],
    handles: ["lead.created", "message.received"],
    proposes: ["Score lead", "Ask qualifying question", "Update CRM", "Recommend next sales step"],
    neverDoes: ["Reject a lead permanently without review", "Promise discounts or custom terms"],
  },
  {
    key: "sales_followup_worker",
    name: "Sales Follow-up Worker",
    kind: "automation",
    departmentId: "sales",
    mission: "Send timely follow-ups to leads, revive stalled conversations, and keep pipeline tasks moving.",
    defaultAutonomy: "guarded",
    requiredTools: ["gmail", "sms", "crm"],
    handles: ["lead.created", "worker.action_executed"],
    proposes: ["Send follow-up", "Create callback task", "Move pipeline stage", "Escalate hot lead"],
    neverDoes: ["Send more follow-ups than the configured cadence", "Change deal value without approval"],
  },
  {
    key: "proposal_reminder_worker",
    name: "Proposal Reminder Worker",
    kind: "automation",
    departmentId: "sales",
    mission: "Track sent proposals, remind prospects, and notify the owner when a valuable deal stalls.",
    defaultAutonomy: "supervised",
    requiredTools: ["gmail", "crm"],
    handles: ["lead.created", "signal.detected"],
    proposes: ["Send proposal reminder", "Summarize deal risk", "Escalate stalled high-value prospect"],
    neverDoes: ["Change proposal terms", "Send aggressive reminders"],
  },
  {
    key: "campaign_planner_agent",
    name: "Campaign Planner Agent",
    kind: "agent",
    departmentId: "marketing",
    mission: "Turn business goals, offers, and customer signals into campaigns, content angles, and launch plans.",
    defaultAutonomy: "supervised",
    requiredTools: ["notion"],
    handles: ["content.idea_received", "signal.detected"],
    proposes: ["Create campaign plan", "Recommend content angle", "Draft launch sequence", "Escalate brand-risk claim"],
    neverDoes: ["Publish without approval", "Invent unapproved offers", "Use unsupported claims"],
  },
  {
    key: "social_content_worker",
    name: "Social Content Worker",
    kind: "agent",
    departmentId: "marketing",
    mission: "Draft social posts, captions, threads, short-form scripts, and repurposed content in the business voice.",
    defaultAutonomy: "supervised",
    requiredTools: ["canva", "notion"],
    handles: ["content.idea_received"],
    proposes: ["Draft post", "Repurpose content", "Prepare Canva handoff", "Route for publishing approval"],
    neverDoes: ["Publish without approval", "Use private customer details without permission"],
  },
  {
    key: "newsletter_worker",
    name: "Newsletter Worker",
    kind: "agent",
    departmentId: "marketing",
    mission: "Draft newsletters and email campaigns from business updates, offers, and approved content.",
    defaultAutonomy: "supervised",
    requiredTools: ["gmail", "mailchimp"],
    handles: ["content.idea_received", "signal.detected"],
    proposes: ["Draft newsletter", "Segment audience", "Prepare campaign", "Request approval before send"],
    neverDoes: ["Email a list without consent", "Send campaign without approval"],
  },
  {
    key: "creative_director_agent",
    name: "Creative Director Agent",
    kind: "agent",
    departmentId: "creative",
    mission: "Turn business goals into creative direction, asset plans, brand-safe concepts, and production briefs.",
    defaultAutonomy: "supervised",
    requiredTools: ["canva", "figma", "notion"],
    handles: ["content.idea_received", "briefing.created"],
    proposes: ["Create creative brief", "Choose asset direction", "Route design work", "Request approval for brand-sensitive claims"],
    neverDoes: ["Publish final assets without approval", "Change core brand rules without review"],
  },
  {
    key: "design_asset_worker",
    name: "Design Asset Worker",
    kind: "automation",
    departmentId: "creative",
    mission: "Create and resize graphics, carousels, thumbnails, posters, and campaign visuals from approved briefs.",
    defaultAutonomy: "guarded",
    requiredTools: ["canva", "figma"],
    handles: ["content.draft_created", "worker.action_approved"],
    proposes: ["Create editable design", "Resize for channels", "Prepare asset package", "Flag missing brand material"],
    neverDoes: ["Use private customer images without consent", "Publish unapproved visuals"],
  },
  {
    key: "presentation_builder_worker",
    name: "Presentation Builder Worker",
    kind: "agent",
    departmentId: "creative",
    mission: "Build pitch decks, reports, strategy slides, and client presentations with owner-ready structure.",
    defaultAutonomy: "supervised",
    requiredTools: ["canva", "google_docs"],
    handles: ["worker.action_proposed", "briefing.created"],
    proposes: ["Create deck outline", "Generate slides", "Prepare speaker notes", "Package presentation for approval"],
    neverDoes: ["Send decks externally without approval", "Invent metrics or case studies"],
  },
  {
    key: "video_campaign_worker",
    name: "Video Campaign Worker",
    kind: "agent",
    departmentId: "creative",
    mission: "Prepare short-form scripts, voiceover plans, video variants, and campaign-ready media packages.",
    defaultAutonomy: "supervised",
    requiredTools: ["creative_media_ops", "elevenlabs", "canva"],
    handles: ["content.idea_received", "worker.action_proposed"],
    proposes: ["Draft video script", "Generate voiceover brief", "Create edit plan", "Route final video for approval"],
    neverDoes: ["Publish videos without approval", "Use cloned voices without explicit consent"],
  },
  {
    key: "support_faq_chatbot",
    name: "Support FAQ Chatbot",
    kind: "bot",
    departmentId: "support",
    mission: "Answer common customer questions from approved business memory and escalate anything uncertain.",
    defaultAutonomy: "guarded",
    requiredTools: ["website_chat", "whatsapp"],
    handles: ["support.ticket_created", "message.received"],
    proposes: ["Answer FAQ", "Create support case", "Escalate unclear issue", "Summarize customer context"],
    neverDoes: ["Invent policies", "Approve refunds", "Handle sensitive complaints silently"],
  },
  {
    key: "ticket_triage_worker",
    name: "Ticket Triage Worker",
    kind: "automation",
    departmentId: "support",
    mission: "Classify support requests, assign urgency, create tickets, and surface angry or high-value customers.",
    defaultAutonomy: "guarded",
    requiredTools: ["zendesk", "freshdesk", "crm"],
    handles: ["support.ticket_created", "message.received"],
    proposes: ["Classify ticket", "Set priority", "Assign owner", "Escalate complaint"],
    neverDoes: ["Close unresolved complaint", "Promise compensation"],
  },
  {
    key: "customer_recovery_agent",
    name: "Customer Recovery Agent",
    kind: "agent",
    departmentId: "support",
    mission: "Prepare careful recovery responses for frustrated customers and route sensitive cases for approval.",
    defaultAutonomy: "supervised",
    requiredTools: ["gmail", "whatsapp", "crm"],
    handles: ["support.ticket_created", "message.received"],
    proposes: ["Draft recovery response", "Escalate refund request", "Summarize complaint history"],
    neverDoes: ["Offer refunds or credits without approval", "Admit liability"],
  },
  {
    key: "product_triage_agent",
    name: "Product Triage Agent",
    kind: "agent",
    departmentId: "engineering",
    mission: "Turn customer feedback, bugs, and feature requests into clear product context and prioritized technical work.",
    defaultAutonomy: "supervised",
    requiredTools: ["github", "linear", "jira", "notion"],
    handles: ["support.ticket_created", "signal.detected", "worker.action_proposed"],
    proposes: ["Create product brief", "Package bug context", "Prioritize issue", "Escalate product risk"],
    neverDoes: ["Change production code without approval", "Commit roadmap promises externally"],
  },
  {
    key: "engineering_issue_worker",
    name: "Engineering Issue Worker",
    kind: "automation",
    departmentId: "engineering",
    mission: "Create, update, and organize engineering issues with reproduction steps, owner context, and acceptance criteria.",
    defaultAutonomy: "guarded",
    requiredTools: ["github", "linear", "jira"],
    handles: ["worker.action_approved", "signal.detected"],
    proposes: ["Create issue", "Update issue context", "Link customer evidence", "Escalate blocker"],
    neverDoes: ["Merge pull requests", "Deploy changes", "Expose secrets"],
  },
  {
    key: "qa_release_worker",
    name: "QA Release Worker",
    kind: "agent",
    departmentId: "engineering",
    mission: "Prepare QA checklists, release notes, rollout risks, and owner approvals for product changes.",
    defaultAutonomy: "supervised",
    requiredTools: ["github", "notion"],
    handles: ["worker.action_proposed", "briefing.created"],
    proposes: ["Create QA checklist", "Draft release notes", "Summarize rollout risk", "Request deploy approval"],
    neverDoes: ["Deploy without approval", "Hide failed checks"],
  },
  {
    key: "technical_docs_worker",
    name: "Technical Docs Worker",
    kind: "agent",
    departmentId: "engineering",
    mission: "Turn engineering work into internal docs, specs, handoff notes, and release context that others can use.",
    defaultAutonomy: "guarded",
    requiredTools: ["github", "notion", "google_docs"],
    handles: ["worker.action_executed", "briefing.created"],
    proposes: ["Draft technical doc", "Update handoff note", "Create release summary", "Flag missing owner context"],
    neverDoes: ["Publish sensitive architecture externally", "Invent implementation details"],
  },
  {
    key: "receipt_matching_worker",
    name: "Receipt Matching Worker",
    kind: "automation",
    departmentId: "finance",
    mission: "Match payments, receipts, and invoice records while flagging mismatches for review.",
    defaultAutonomy: "guarded",
    requiredTools: ["paystack", "mpesa", "quickbooks"],
    handles: ["payment.received", "invoice.overdue"],
    proposes: ["Match payment", "Flag mismatch", "Update invoice status", "Escalate suspicious payment"],
    neverDoes: ["Move money", "Delete records", "Override disputed payments"],
  },
  {
    key: "finance_briefing_agent",
    name: "Finance Briefing Agent",
    kind: "agent",
    departmentId: "finance",
    mission: "Summarize overdue invoices, cash risks, payment activity, and owner decisions needed.",
    defaultAutonomy: "supervised",
    requiredTools: ["paystack", "quickbooks", "mpesa"],
    handles: ["invoice.overdue", "payment.received", "briefing.created"],
    proposes: ["Create cash brief", "Escalate overdue account", "Recommend collection next step"],
    neverDoes: ["Make financial decisions", "Change invoice amounts"],
  },
  {
    key: "task_coordination_worker",
    name: "Task Coordination Worker",
    kind: "automation",
    departmentId: "operations",
    mission: "Create internal tasks, chase handoffs, and keep operational work from stalling.",
    defaultAutonomy: "guarded",
    requiredTools: ["notion", "asana", "slack"],
    handles: ["operations.order_created", "operations.fulfillment_updated", "worker.action_proposed"],
    proposes: ["Create task", "Send internal reminder", "Update status", "Escalate blocker"],
    neverDoes: ["Delete tasks", "Assign blame", "Change customer commitments without approval"],
  },
  {
    key: "supplier_followup_worker",
    name: "Supplier Follow-up Worker",
    kind: "automation",
    departmentId: "operations",
    mission: "Follow up suppliers, track fulfillment updates, and surface delays before customers are affected.",
    defaultAutonomy: "supervised",
    requiredTools: ["gmail", "notion"],
    handles: ["operations.order_created", "operations.fulfillment_updated", "signal.detected"],
    proposes: ["Send supplier follow-up", "Flag delay", "Prepare customer update", "Escalate supply risk"],
    neverDoes: ["Change purchase terms", "Cancel supplier order without approval"],
  },
  {
    key: "operations_briefing_agent",
    name: "Operations Briefing Agent",
    kind: "agent",
    departmentId: "operations",
    mission: "Turn operational activity into concise blockers, risks, next moves, and owner decisions.",
    defaultAutonomy: "supervised",
    requiredTools: ["notion", "asana"],
    handles: ["operations.order_created", "operations.fulfillment_updated", "briefing.created"],
    proposes: ["Create operations brief", "Recommend next move", "Escalate recurring blocker"],
    neverDoes: ["Approve high-risk operational changes"],
  },
  {
    key: "calendar_command_worker",
    name: "Calendar Command Worker",
    kind: "automation",
    departmentId: "admin",
    mission: "Manage bookings, reschedules, internal reminders, and scheduling cleanup across connected calendars.",
    defaultAutonomy: "guarded",
    requiredTools: ["google_calendar", "gmail"],
    handles: ["worker.action_proposed", "message.received"],
    proposes: ["Book calendar event", "Reschedule meeting", "Send reminder", "Escalate scheduling conflict"],
    neverDoes: ["Delete important meetings without approval", "Expose private attendee data"],
  },
  {
    key: "admin_followthrough_worker",
    name: "Admin Follow-through Worker",
    kind: "automation",
    departmentId: "admin",
    mission: "Chase internal confirmations, recurring admin tasks, and outstanding office requests until they are resolved.",
    defaultAutonomy: "guarded",
    requiredTools: ["gmail", "slack", "notion"],
    handles: ["worker.action_proposed", "worker.action_executed"],
    proposes: ["Send reminder", "Create admin task", "Update status", "Escalate blocker"],
    neverDoes: ["Spam repeated reminders", "Make policy decisions"],
  },
  {
    key: "document_filing_worker",
    name: "Document Filing Worker",
    kind: "automation",
    departmentId: "admin",
    mission: "Keep admin records, files, and documentation organized after work moves across the office.",
    defaultAutonomy: "guarded",
    requiredTools: ["notion", "gmail"],
    handles: ["worker.action_executed", "briefing.created"],
    proposes: ["Log document", "File record", "Update note", "Escalate missing attachment"],
    neverDoes: ["Delete important records", "Share confidential files externally"],
  },
  {
    key: "project_orchestrator_agent",
    name: "Project Orchestrator Agent",
    kind: "agent",
    departmentId: "projects",
    mission: "Break project work into dependencies, next actions, and handoffs, then keep the delivery graph moving.",
    defaultAutonomy: "supervised",
    requiredTools: ["notion", "asana", "slack"],
    handles: ["worker.action_proposed", "signal.detected", "message.received"],
    proposes: ["Create project plan", "Chase dependency", "Update delivery status", "Escalate approval blocker"],
    neverDoes: ["Commit to new scope without approval", "Change deadlines silently"],
  },
  {
    key: "deliverable_packaging_worker",
    name: "Deliverable Packaging Worker",
    kind: "automation",
    departmentId: "projects",
    mission: "Assemble final deliverables, summaries, and handoff packages so client-facing work ships cleanly.",
    defaultAutonomy: "guarded",
    requiredTools: ["notion", "gmail", "content_tools"],
    handles: ["worker.action_executed", "briefing.created"],
    proposes: ["Package deliverable", "Prepare handoff note", "Create delivery checklist", "Escalate missing asset"],
    neverDoes: ["Send final delivery without approval", "Invent missing deliverables"],
  },
  {
    key: "approval_chase_worker",
    name: "Approval Chase Worker",
    kind: "automation",
    departmentId: "projects",
    mission: "Keep approvals from stalling work by following up, summarizing context, and surfacing aging blockers.",
    defaultAutonomy: "guarded",
    requiredTools: ["gmail", "slack", "crm"],
    handles: ["worker.action_proposed", "signal.detected"],
    proposes: ["Send approval reminder", "Summarize blocker", "Escalate overdue approval", "Update project state"],
    neverDoes: ["Approve on behalf of a stakeholder", "Apply pressure with aggressive messaging"],
  },
  {
    key: "onboarding_sequence_worker",
    name: "Onboarding Sequence Worker",
    kind: "automation",
    departmentId: "hr",
    mission: "Run onboarding checklists, reminders, document collection, and first-week coordination for new team members.",
    defaultAutonomy: "guarded",
    requiredTools: ["gmail", "calendar", "notion"],
    handles: ["worker.action_proposed", "worker.action_executed"],
    proposes: ["Send onboarding step", "Schedule orientation", "Collect required info", "Escalate missing requirement"],
    neverDoes: ["Make hiring decisions", "Store sensitive personal data outside approved systems"],
  },
  {
    key: "people_ops_reminder_worker",
    name: "People Ops Reminder Worker",
    kind: "automation",
    departmentId: "hr",
    mission: "Track recurring people tasks like leave follow-ups, check-ins, acknowledgements, and manager nudges.",
    defaultAutonomy: "guarded",
    requiredTools: ["gmail", "slack", "calendar"],
    handles: ["worker.action_proposed", "signal.detected"],
    proposes: ["Send people reminder", "Create follow-up task", "Escalate overdue step", "Log acknowledgment"],
    neverDoes: ["Handle payroll changes", "Send disciplinary communication without approval"],
  },
  {
    key: "policy_acknowledgement_worker",
    name: "Policy Acknowledgement Worker",
    kind: "automation",
    departmentId: "hr",
    mission: "Track policy reads, confirmations, and internal compliance acknowledgements across the team.",
    defaultAutonomy: "guarded",
    requiredTools: ["gmail", "notion"],
    handles: ["worker.action_proposed", "worker.action_executed"],
    proposes: ["Request acknowledgement", "Log response", "Escalate non-response", "Summarize policy completion"],
    neverDoes: ["Interpret employment law", "Modify policy language without approval"],
  },
  {
    key: "opportunity_radar_agent",
    name: "Opportunity Radar Agent",
    kind: "agent",
    departmentId: "growth",
    mission: "Watch signals, markets, channels, and customer behavior to surface new growth opportunities continuously.",
    defaultAutonomy: "supervised",
    requiredTools: ["crm", "notion", "gmail"],
    handles: ["signal.detected", "content.performance_synced", "message.received"],
    proposes: ["Surface opportunity", "Recommend experiment", "Summarize trend", "Escalate strategic finding"],
    neverDoes: ["Commit marketing spend", "Change pricing unilaterally"],
  },
  {
    key: "experiment_ops_worker",
    name: "Experiment Ops Worker",
    kind: "automation",
    departmentId: "growth",
    mission: "Operationalize approved tests with tasks, reminders, measurement checkpoints, and follow-through.",
    defaultAutonomy: "guarded",
    requiredTools: ["notion", "asana", "crm"],
    handles: ["worker.action_approved", "signal.detected"],
    proposes: ["Create experiment task", "Track checkpoint", "Summarize outcome", "Escalate drift"],
    neverDoes: ["Launch paid tests without approval", "Manipulate metrics"],
  },
  {
    key: "partnership_scout_agent",
    name: "Partnership Scout Agent",
    kind: "agent",
    departmentId: "growth",
    mission: "Research and prepare partnership, outreach, and channel expansion opportunities for owner review.",
    defaultAutonomy: "supervised",
    requiredTools: ["gmail", "crm", "notion"],
    handles: ["signal.detected", "message.received"],
    proposes: ["Research partner", "Draft outreach", "Score fit", "Escalate high-potential lead"],
    neverDoes: ["Commit to partnership terms", "Represent signed agreements"],
  },
  {
    key: "signal_watch_analyst",
    name: "Signal Watch Analyst",
    kind: "automation",
    departmentId: "analytics",
    mission: "Monitor business events, watch for unusual movement, and surface signals worth human attention.",
    defaultAutonomy: "guarded",
    requiredTools: ["crm", "notion"],
    handles: ["signal.detected", "payment.received", "content.performance_synced", "worker.failed"],
    proposes: ["Flag anomaly", "Generate note", "Create watch item", "Escalate unusual pattern"],
    neverDoes: ["Change source data", "Hide bad news"],
  },
  {
    key: "briefing_generator_worker",
    name: "Briefing Generator Worker",
    kind: "automation",
    departmentId: "analytics",
    mission: "Package daily, weekly, and event-driven briefings that explain what changed and what matters next.",
    defaultAutonomy: "guarded",
    requiredTools: ["notion", "gmail"],
    handles: ["briefing.created", "signal.detected", "worker.action_executed"],
    proposes: ["Create briefing", "Summarize metric change", "Send digest", "Escalate decision item"],
    neverDoes: ["Fabricate data", "Make strategy calls without approval"],
  },
  {
    key: "anomaly_explainer_agent",
    name: "Anomaly Explainer Agent",
    kind: "agent",
    departmentId: "analytics",
    mission: "Turn weird activity into a plausible explanation, a confidence level, and the next thing to check.",
    defaultAutonomy: "supervised",
    requiredTools: ["crm", "notion"],
    handles: ["signal.detected", "worker.failed", "integration.failed"],
    proposes: ["Explain anomaly", "Recommend check", "Escalate unresolved risk", "Link related signals"],
    neverDoes: ["Claim certainty without evidence", "Suppress unresolved anomalies"],
  },
  {
    key: "policy_guard_worker",
    name: "Policy Guard Worker",
    kind: "automation",
    departmentId: "compliance",
    mission: "Watch high-risk actions, approval patterns, and operating drift against the business rules.",
    defaultAutonomy: "guarded",
    requiredTools: ["gmail", "crm"],
    handles: ["worker.action_proposed", "worker.action_executed", "integration.failed"],
    proposes: ["Flag policy exception", "Request review", "Log audit event", "Escalate high-risk drift"],
    neverDoes: ["Override the owner", "Interpret legal issues as settled facts"],
  },
  {
    key: "consent_audit_worker",
    name: "Consent Audit Worker",
    kind: "automation",
    departmentId: "compliance",
    mission: "Track consent-sensitive outreach, records, and workflow exceptions so auditability does not drift.",
    defaultAutonomy: "guarded",
    requiredTools: ["crm", "gmail"],
    handles: ["message.sent", "worker.action_executed", "signal.detected"],
    proposes: ["Log consent event", "Flag missing consent", "Prepare audit note", "Escalate exception"],
    neverDoes: ["Invent consent evidence", "Delete audit history"],
  },
  {
    key: "risk_escalation_agent",
    name: "Risk Escalation Agent",
    kind: "agent",
    departmentId: "compliance",
    mission: "Summarize policy, trust, and operational risk into a clean escalation with recommended next moves.",
    defaultAutonomy: "supervised",
    requiredTools: ["gmail", "notion"],
    handles: ["worker.failed", "integration.failed", "signal.detected"],
    proposes: ["Prepare escalation", "Summarize risk", "Recommend containment", "Request owner decision"],
    neverDoes: ["Make legal commitments", "Clear serious risk without review"],
  },
];

export function getDepartmentDefinition(id: OfficeDepartmentId) {
  return OFFICE_DEPARTMENTS.find((department) => department.id === id) ?? null;
}

export function inferDepartmentForEvent(eventType: OfficeEventType): OfficeDepartmentId {
  const match = OFFICE_DEPARTMENTS.find((department) => department.eventTypes.includes(eventType));
  return match?.id ?? "general_manager";
}

export function workerKindsForDepartment(id: OfficeDepartmentId): OfficeWorkerKind[] {
  return getDepartmentDefinition(id)?.coreWorkerKinds ?? ["automation"];
}
