/**
 * Anti-AI Prompt Engineering
 * Prompts and techniques to generate human-like text that avoids AI detection patterns
 */

export interface AntiAIPromptConfig {
  personality: "casual" | "professional" | "academic" | "creative";
  tone: "direct" | "friendly" | "formal" | "conversational";
  complexity: "simple" | "moderate" | "complex";
  constraints: string[];
}

/**
 * Generate system prompt that avoids AI patterns
 */
export function generateAntiAISystemPrompt(config: AntiAIPromptConfig): string {
  const baseConstraints = [
    "Write like a human, not an AI",
    "Use simple, direct language",
    "Avoid corporate jargon and buzzwords",
    "Be specific and concrete, not abstract",
    "Use varied sentence structures",
    "Write in active voice",
    "Keep sentences under 20 words when possible",
    "Avoid lists of three parallel items",
    "Don't use phrases like 'in conclusion', 'furthermore', 'moreover'",
    "Use 'is' and 'are' naturally",
    "Avoid words like: crucial, pivotal, enhance, showcase, delve, tapestry, landscape",
    "Be authentic and genuine",
    "Write as if talking to a friend or colleague",
  ];

  const personalityPrompts = {
    casual: "Write as if you're texting a friend. Use contractions, simple words, and a relaxed tone.",
    professional: "Write as a competent professional. Be clear, direct, and authoritative but not stuffy.",
    academic: "Write as a knowledgeable expert. Be precise but avoid academic jargon and overly complex sentences.",
    creative: "Write with imagination and flair. Use metaphors and vivid descriptions naturally.",
  };

  const tonePrompts = {
    direct: "Get straight to the point. No fluff or filler.",
    friendly: "Be warm and approachable. Use 'you' and 'we' appropriately.",
    formal: "Maintain professional distance but be clear and helpful.",
    conversational: "Write as if having a conversation. Ask questions, use natural transitions.",
  };

  const complexityPrompts = {
    simple: "Use basic vocabulary. Explain complex ideas simply.",
    moderate: "Use standard vocabulary. Mix simple and complex sentences.",
    complex: "Use precise terminology when needed, but explain it clearly.",
  };

  return `
You are a helpful assistant that writes naturally and avoids AI detection patterns.

${personalityPrompts[config.personality]}

${tonePrompts[config.tone]}

${complexityPrompts[config.complexity]}

CRITICAL CONSTRAINTS:
${baseConstraints.concat(config.constraints).map(c => `- ${c}`).join('\n')}

Remember: Your goal is to sound completely human and natural. Avoid anything that sounds like it was generated by an AI.
  `.trim();
}

/**
 * Generate user prompt template
 */
export function generateAntiAIUserPrompt(
  task: string,
  context?: string,
  examples?: string[]
): string {
  let prompt = `Task: ${task}`;

  if (context) {
    prompt += `\n\nContext: ${context}`;
  }

  if (examples && examples.length > 0) {
    prompt += `\n\nExamples of natural human writing:\n${examples.map((ex, i) => `${i + 1}. ${ex}`).join('\n')}`;
  }

  prompt += `

Please write this naturally, as a human would. Avoid:
- Corporate buzzwords and jargon
- Overly complex sentences
- Repetitive sentence structures
- AI vocabulary words
- Formal constructions that sound unnatural

Write directly and authentically.`;

  return prompt;
}

/**
 * Pre-built prompt configurations for different use cases
 */
export const ANTI_AI_CONFIGS = {
  customer_service: {
    personality: "friendly" as const,
    tone: "conversational" as const,
    complexity: "simple" as const,
    constraints: [
      "Be empathetic and understanding",
      "Use contractions naturally",
      "Keep responses under 3 sentences when possible",
      "Focus on solving the problem",
    ],
  },
  business_communication: {
    personality: "professional" as const,
    tone: "direct" as const,
    complexity: "moderate" as const,
    constraints: [
      "Be clear and concise",
      "Use active voice",
      "Avoid corporate jargon",
      "Focus on action and results",
    ],
  },
  creative_writing: {
    personality: "creative" as const,
    tone: "friendly" as const,
    complexity: "moderate" as const,
    constraints: [
      "Use vivid descriptions",
      "Vary sentence length",
      "Show, don't just tell",
      "Use natural dialogue",
    ],
  },
  technical_documentation: {
    personality: "professional" as const,
    tone: "direct" as const,
    complexity: "complex" as const,
    constraints: [
      "Be precise and accurate",
      "Define technical terms simply",
      "Use examples to clarify",
      "Organize logically",
    ],
  },
};

/**
 * Chain-of-thought prompt to avoid AI patterns
 */
export function generateChainOfThoughtPrompt(
  topic: string,
  keyPoints: string[]
): string {
  return `
Think through this step by step, like a human would naturally process information:

1. First, consider the main topic: ${topic}
2. What are the key points to cover?
${keyPoints.map((point, i) => `   ${i + 2}. ${point}`).join('\n')}
3. How would a real person explain this to someone else?
4. What natural examples or analogies come to mind?
5. How can I structure this to flow naturally?

Now write your response thinking through these points, but write it naturally as if you're explaining it to someone. Don't follow a rigid structure - let it flow naturally.

Remember:
- Use simple, everyday language
- Be direct and clear
- Avoid AI vocabulary
- Write like you're talking to a person
`;
}

/**
 * Few-shot examples to guide natural writing
 */
export const NATURAL_WRITING_EXAMPLES = {
  emails: [
    "Hey Sarah, just wanted to check in on the project. How's it going? Let me know if you need anything.",
    "Thanks for sending over the report. I looked through it and have a few questions. Can we chat tomorrow afternoon?",
  ],
  messages: [
    "I'm not sure about that approach. Maybe we should try something simpler?",
    "Good point! I didn't think of it that way. Let's incorporate that.",
  ],
  descriptions: [
    "The room was bright and airy, with big windows overlooking the garden. A wooden table sat in the center, surrounded by mismatched chairs that looked like they'd been collected over years.",
  ],
};

/**
 * Generate prompt with examples
 */
export function generatePromptWithExamples(
  task: string,
  category: keyof typeof NATURAL_WRITING_EXAMPLES
): string {
    const examples = NATURAL_WRITING_EXAMPLES[category];
    
    return generateAntiAIUserPrompt(
      task,
      `Here are examples of natural human ${category}:`,
      examples
    );
}
